#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.upload_gradebook.py
# Version:      1.0.0
# Date:         2026-04-23
# Purpose:      Upload grades from a Canvas-format gradebook CSV to a Canvas
#               course. Assignment columns are matched by name or ID suffix.
#               Assignments not found in Canvas can be created automatically.
#
# Usage:        canvas.api.upload_gradebook.py COURSE_ID CSV_FILE
#                   [--create-missing] [--group-id ID] [--points N]
#                   [-n, --dry-run] [-v, --verbose] [-h, --help]
#
# Input:        Canvas-format gradebook CSV. Standard columns (Student, ID,
#               SIS User ID, SIS Login ID, Section) are used for student
#               lookup. Remaining columns are treated as assignments. Headers
#               may be plain names or "Name (assignment_id)" format.
#               Row with "Points Possible" in Student column is skipped.
#               Rows with empty Canvas user ID (column "ID") are skipped.
#
# Output:       Progress messages to stderr; summary to stdout.
#
# Options:
#   --create-missing    Create Canvas assignments not found by name/ID
#   --group-id ID       Assignment group ID for newly created assignments
#   --points N          Default points_possible for created assignments (1.0)
#   -n, --dry-run       Show actions without making changes
#   -v, --verbose       Show per-grade update messages
#   -h, --help          Show this help message
#
# Requirements:
#   - ~/.canvas.api.conf with base_url and token_file
#   - Canvas API token readable at token_file path
#
# Session:      catme.iii.upload
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Sonnet 4.6
# ============================================================================

import argparse
import csv as csvmod
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from canvas_api import get_assignments
from canvas_http import http_post_json, http_put_json
from io_utils import load_profile, read_token


# -- Colors ------------------------------------------------------------------

if sys.stderr.isatty():
    GREEN  = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED    = '\033[0;31m'
    BLUE   = '\033[0;34m'
    NC     = '\033[0m'
else:
    GREEN = YELLOW = RED = BLUE = NC = ''


def ok(msg):   print(f"  {GREEN}ok{NC}  {msg}", file=sys.stderr)
def warn(msg): print(f"  {YELLOW}warn{NC} {msg}", file=sys.stderr)
def err(msg):  print(f"  {RED}err{NC}  {msg}", file=sys.stderr)
def info(msg): print(f"  {BLUE}info{NC} {msg}", file=sys.stderr)


# -- Helpers -----------------------------------------------------------------

STANDARD_COLS = {"Student", "ID", "SIS User ID", "SIS Login ID", "Section"}


def parse_col_header(header):
    """Return (name, assignment_id_or_None) from 'Name (12345)' or 'Name'."""
    m = re.match(r'^(.*)\s+\((\d+)\)\s*$', header)
    if m:
        return m.group(1).strip(), int(m.group(2))
    return header.strip(), None


def find_by_name(assignments, name):
    """Case-insensitive assignment name search; return first match or None."""
    nl = name.lower()
    for a in assignments:
        if a['name'].lower() == nl:
            return a
    return None


def create_assignment(base_url, token, course_id, name, points, group_id,
                      dry_run=False, verbose=False):
    """Create a Canvas assignment with no-submission type."""
    if dry_run:
        ok(f"[dry-run] would create '{name}' ({points}pt, group={group_id})")
        return {"id": 0, "name": name, "points_possible": points}

    body = {
        "assignment": {
            "name": name,
            "points_possible": points,
            "submission_types": ["none"],
            "published": True,
            "grading_type": "points",
        }
    }
    if group_id:
        body["assignment"]["assignment_group_id"] = group_id

    result, _ = http_post_json(
        f"{base_url}/api/v1/courses/{course_id}/assignments", token, body)
    ok(f"created '{result['name']}' (id={result['id']}, {result['points_possible']}pt)")
    return result


def update_submission(base_url, token, course_id, assignment_id, user_id,
                      grade, dry_run=False, verbose=False):
    """PUT a grade onto a student's submission."""
    if dry_run:
        if verbose:
            ok(f"[dry-run] user {user_id} asgn {assignment_id}: {grade}")
        return

    url = (f"{base_url}/api/v1/courses/{course_id}/assignments"
           f"/{assignment_id}/submissions/{user_id}")
    http_put_json(url, token, {"submission": {"posted_grade": str(grade)}})
    if verbose:
        ok(f"user {user_id} asgn {assignment_id}: {grade}")


# -- Main --------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="Upload grades from Canvas-format gradebook CSV.")
    ap.add_argument("course_id", type=int, help="Canvas course ID")
    ap.add_argument("csv_file", help="Path to gradebook CSV")
    ap.add_argument("--create-missing", action="store_true",
                    help="Create Canvas assignments not found by name")
    ap.add_argument("--group-id", type=int,
                    help="Assignment group ID for created assignments")
    ap.add_argument("--points", type=float, default=1.0,
                    help="points_possible for created assignments (default: 1.0)")
    ap.add_argument("--base-url", help="Canvas instance base URL")
    ap.add_argument("--token", help="Canvas API token (inline)")
    ap.add_argument("--token-file", help="Path to token file")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show what would be done without making changes")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show per-grade update messages")
    ap.add_argument("-h2", "--help2", action="help",
                    default=argparse.SUPPRESS,
                    help=argparse.SUPPRESS)
    args = ap.parse_args()

    profile = load_profile()
    base_url = (args.base_url or profile.get("base_url", "")).rstrip("/")
    if not base_url:
        err("no base_url: pass --base-url or set in ~/.canvas.api.conf")
        sys.exit(1)
    token = read_token(args.token, args.token_file, profile)

    # -- Read CSV ------------------------------------------------------------
    with open(args.csv_file, newline="", encoding="utf-8") as f:
        reader = csvmod.DictReader(f)
        all_rows = list(reader)
        all_cols = reader.fieldnames or []

    # Identify assignment columns
    asgn_cols = [c for c in all_cols if c not in STANDARD_COLS]
    if not asgn_cols:
        err("no assignment columns found in CSV")
        sys.exit(1)

    # Separate points-possible row from student data rows
    student_rows = []
    for row in all_rows:
        s = row.get("Student", "").strip()
        if "Points Possible" in s:
            continue                 # skip the points row
        if not s:
            continue                 # skip blank rows
        student_rows.append(row)

    info(f"CSV: {len(asgn_cols)} assignment column(s), {len(student_rows)} student row(s)")

    # -- Match assignment columns to Canvas assignments ----------------------
    canvas_asgns = get_assignments(base_url, token, args.course_id,
                                    verbose=args.verbose)
    asgn_map = {}   # col_name -> canvas assignment dict

    for col in asgn_cols:
        name, hint_id = parse_col_header(col)
        found = None

        # 1. Try ID hint
        if hint_id:
            for a in canvas_asgns:
                if a['id'] == hint_id:
                    found = a
                    break

        # 2. Try name match
        if not found:
            found = find_by_name(canvas_asgns, name)

        if found:
            ok(f"matched '{col}' -> id={found['id']} '{found['name']}'")
            asgn_map[col] = found
        elif args.create_missing:
            new_a = create_assignment(base_url, token, args.course_id,
                                       name, args.points, args.group_id,
                                       dry_run=args.dry_run,
                                       verbose=args.verbose)
            asgn_map[col] = new_a
        else:
            warn(f"no assignment found for '{col}' -- skipping "
                 f"(use --create-missing to create it)")

    if not asgn_map:
        err("no assignments resolved; nothing to upload")
        sys.exit(1)

    # -- Upload grades -------------------------------------------------------
    updated = skipped = empty = 0

    for row in student_rows:
        student = row.get("Student", "").strip()
        user_id = row.get("ID", "").strip()

        if not user_id:
            warn(f"skipping '{student}': no Canvas user ID")
            skipped += 1
            continue

        for col, asgn in asgn_map.items():
            grade = row.get(col, "").strip()
            if not grade:
                empty += 1
                if args.verbose:
                    info(f"{student}: '{col}' is empty, skipping")
                continue

            update_submission(base_url, token, args.course_id, asgn['id'],
                               user_id, grade,
                               dry_run=args.dry_run, verbose=args.verbose)
            updated += 1

    action = "[dry-run] would update" if args.dry_run else "updated"
    ok(f"done: {action} {updated} grade(s); {empty} empty cell(s) skipped; "
       f"{skipped} student(s) skipped (no ID)")


if __name__ == "__main__":
    main()
