#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.check_db_points.py
# Version:      1.0.0
# Date:         2026-03-18
# Purpose:      Verify that all lecture-specific discussion board assignments
#               in a Canvas course are worth the expected number of points
#               (default: 5.0).
#
# Usage:        canvas.api.check_db_points.py COURSE_ID [--points N]
#                   [--base-url URL] [--token TOKEN | --token-file FILE]
#                   [--dry-run] [--verbose] [--help]
#
# Input:        Canvas API token + course_id (or ~/.canvas.api.conf)
# Output:       Per-topic point check on stdout; exit 0 if all ok, 1 if not
#
# Options:
#   --points N             Expected point value (default: 5.0)
#   --base-url URL         Canvas instance URL (or set in ~/.canvas.api.conf)
#   --token TOKEN          Inline API token
#   --token-file FILE      Path to token file (or set in ~/.canvas.api.conf)
#   -n, --dry-run          Show what would be checked without API calls
#   -v, --verbose          Show detailed output
#   -h, --help             Show this help message
#
# Requirements:
#   - Python 3.7+
#   - Canvas API token with instructor access to the course
#
# Session:      Canvas.API Infrastructure
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from canvas_api import get_discussion_topics
from io_utils import (
    extract_session_prefix,
    resolve_credentials,
    session_sort_key,
)


def main():
    ap = argparse.ArgumentParser(
        description="Check that all lecture discussion board assignments "
                    "are worth the expected number of points.")
    ap.add_argument("course_id", type=int,
                    help="Canvas course ID")
    ap.add_argument("--points", type=float, default=5.0,
                    help="Expected point value per DB assignment (default: 5.0)")
    ap.add_argument("--base-url", default=None,
                    help="Canvas instance URL (or set base_url in "
                         "~/.canvas.api.conf)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None,
                    help="Path to token file (or set in ~/.canvas.api.conf)")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show what would be checked without making API calls")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show detailed output")
    args = ap.parse_args()

    if args.dry_run:
        print(f"[DRY RUN] Would fetch discussion topics for course "
              f"{args.course_id} and check points_possible == {args.points}")
        return

    base_url, token = resolve_credentials(args, ap)

    print(f"Fetching discussion topics for course {args.course_id}...")
    topics = get_discussion_topics(base_url, token, args.course_id,
                                   verbose=args.verbose)

    # Filter to lecture-specific topics (title starts with S\d+:)
    lecture_topics = []
    for t in topics:
        prefix = extract_session_prefix(t.get("title", ""))
        if prefix:
            lecture_topics.append((prefix, t))

    if not lecture_topics:
        print("No lecture-specific discussion topics found.")
        return

    # Sort by session number
    lecture_topics.sort(key=lambda pt: session_sort_key(pt[0]))

    ok_count = 0
    bad_count = 0
    no_assignment_count = 0

    print(f"\nChecking {len(lecture_topics)} lecture DB topics "
          f"(expected: {args.points} pts each)\n")

    for prefix, topic in lecture_topics:
        title = topic.get("title", "(untitled)")
        assignment = topic.get("assignment")

        if not assignment:
            print(f"  {prefix:6s}  [WARN] No assignment attached: {title}")
            no_assignment_count = no_assignment_count + 1
            continue

        pts = assignment.get("points_possible")
        published = assignment.get("published", False)
        due = assignment.get("due_at", "")

        if pts == args.points:
            status = "ok"
            ok_count = ok_count + 1
            if args.verbose:
                pub_str = "published" if published else "draft"
                print(f"  {prefix:6s}  [OK]   {pts} pts  ({pub_str})  {title}")
        else:
            status = "MISMATCH"
            bad_count = bad_count + 1
            print(f"  {prefix:6s}  [BAD]  {pts} pts (expected {args.points})  "
                  f"{title}")

    # Summary
    print(f"\nResults: {ok_count} ok", end="")
    if bad_count:
        print(f", {bad_count} MISMATCH", end="")
    if no_assignment_count:
        print(f", {no_assignment_count} no-assignment", end="")
    print(f" (of {len(lecture_topics)} topics)")

    if bad_count:
        sys.exit(1)


if __name__ == "__main__":
    main()
