#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.update_syllabus.py
# Version:      1.0.0
# Date:         2026-04-07
# Purpose:      View, dump, or update a Canvas course's Syllabus page
#               (syllabus_body). Canvas's Syllabus page is stored in the
#               course object, not as a regular wiki page, so it needs a
#               dedicated endpoint.
#
# Usage:
#   canvas.api.update_syllabus.py COURSE_ID --get [-o OUT.html]
#   canvas.api.update_syllabus.py COURSE_ID --set BODY.html
#   canvas.api.update_syllabus.py COURSE_ID --replace OLD:NEW
#                                   [--replace OLD:NEW ...]
#
# Input:        Canvas API token + course_id
# Output:       Current syllabus_body to stdout (or file), or updated body
#
# Options:
#   --get             Print current syllabus_body to stdout
#   -o, --output PATH Write fetched body to PATH instead of stdout
#   --set PATH        Replace syllabus_body with contents of PATH (HTML)
#   --replace OLD:NEW Literal substring replacement in current body
#                     (repeatable). Useful for small in-place edits.
#   -n, --dry-run     Show what would change without writing
#   -v, --verbose     Detailed output
#   -h, --help        Show this help message
#
# Requirements:
#   - Canvas API token in ~/.canvas_token (or via --token/--token-file)
#   - ~/.canvas.api.conf with base_url and token_file
#
# Session:      student.evaluation
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from canvas_api import get_syllabus_body, update_syllabus_body
from io_utils import load_profile, read_token


if sys.stderr.isatty():
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    NC = '\033[0m'
else:
    GREEN = YELLOW = RED = NC = ''


def ok(msg):   print(f"  {GREEN}ok{NC}  {msg}", file=sys.stderr)
def warn(msg): print(f"  {YELLOW}warn{NC} {msg}", file=sys.stderr)
def err(msg):  print(f"  {RED}err{NC}  {msg}", file=sys.stderr)


def parse_replace(s):
    if ":" not in s:
        raise argparse.ArgumentTypeError(
            f"expected OLD:NEW, got '{s}'")
    old, new = s.split(":", 1)
    return old, new


def main():
    parser = argparse.ArgumentParser(
        description="View or update a Canvas course's Syllabus page.")
    parser.add_argument("course_id", type=int, help="Canvas course ID")

    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--get", action="store_true",
                        help="Print current syllabus_body")
    action.add_argument("--set", metavar="PATH",
                        help="Replace syllabus_body with contents of PATH")
    action.add_argument("--replace", type=parse_replace, action="append",
                        metavar="OLD:NEW",
                        help="Literal substring replacement (repeatable)")

    parser.add_argument("-o", "--output", help="Write --get result to file")
    parser.add_argument("--base-url", help="Canvas instance URL")
    parser.add_argument("--token", help="Canvas API token (inline)")
    parser.add_argument("--token-file", help="Path to token file")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="Show changes without writing")
    parser.add_argument("-v", "--verbose", action="store_true")

    args = parser.parse_args()

    profile = load_profile()
    base_url = args.base_url or profile.get("base_url")
    token = read_token(args.token, args.token_file, profile)

    if not base_url:
        err("no base_url: pass --base-url or set in ~/.canvas.api.conf")
        sys.exit(1)

    body = get_syllabus_body(base_url, token, args.course_id,
                             verbose=args.verbose)
    if args.verbose:
        ok(f"fetched syllabus_body ({len(body)} chars)")

    if args.get:
        if args.output:
            with open(args.output, "w") as f:
                f.write(body)
            ok(f"wrote {len(body)} chars to {args.output}")
        else:
            sys.stdout.write(body)
            if not body.endswith("\n"):
                sys.stdout.write("\n")
        return

    if args.set:
        with open(args.set) as f:
            new_body = f.read()
    else:
        new_body = body
        for old, new in args.replace:
            if old not in new_body:
                warn(f"pattern not found: {old[:60]}")
                continue
            new_body = new_body.replace(old, new)

    if new_body == body:
        warn("no changes to apply")
        return

    ok(f"body length: {len(body)} -> {len(new_body)} chars")

    if args.dry_run:
        ok("[dry-run] would PUT updated syllabus_body")
        return

    update_syllabus_body(base_url, token, args.course_id, new_body,
                         verbose=args.verbose)
    ok("syllabus_body updated")


if __name__ == "__main__":
    main()
