#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.clear_late_status.py
# Version:      1.0.0
# Created:      2026-09-08
# Revised:      2026-09-08
# Purpose:      Clear the late flag on submissions whose lateness was waived
#
# Canvas computes `late` from submitted_at against due_at, and that field is
# NOT writable.  What IS writable is `late_policy_status`; setting it to
# "none" tells Canvas to apply no late deduction, which is what an instructor
# means by "the late penalty is waived".
#
# Written for HW01 F.2026, where three teams were given an extension after
# missing files were found: the work arrived on time by the agreed date, and
# Canvas flagging it late would take marks the instructor had already excused.
#
# TOUCHES STUDENT GRADE RECORDS.  It refuses to run without --apply, prints
# every change it would make first, and only ever touches submissions it was
# explicitly asked about -- by group name or by user id.  It never changes a
# grade, only the late-policy status.
#
# Usage:        clear_late_status.py COURSE_ID ASSIGNMENT_ID --base-url URL
#                   [--token-file FILE] [--group NAME]... [--user ID]...
#                   [--status none|late|missing|extended]
#                   [--apply] [--verbose] [--help]
# Input:        Canvas API
# Output:       A line per submission changed; a summary
#
# Options:
#   --base-url URL      Canvas instance URL (required)
#   --token-file FILE   File holding the API token
#   --group NAME        Canvas group (team) to clear, repeatable
#   --user ID           Canvas user id to clear, repeatable
#   --status VALUE      Status to set (default: none = no late penalty)
#   --apply             Actually write.  Without it, nothing is sent.
#   -v, --verbose       Show submissions considered but not changed
#   -h, --help          Show this help message
#
# Requirements:
#   - Python 3.7+, the canvas_http helper in this directory
#
# Session:      grading.interface.for.TAs
# AI Model:     Claude Opus 5
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 5
# ============================================================================

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from canvas_http import (http_get_json, http_put_json,      # noqa: E402
                         parse_next_link)

__version__ = "1.0.0"

VALID = ("none", "late", "missing", "extended")


def read_token(args):
    if args.token:
        return args.token.strip()
    path = os.path.expanduser(args.token_file or "~/.canvas_token")
    with open(path, encoding="utf-8") as fh:
        return fh.read().strip()


def submissions(base, token, course, assignment):
    """All submissions, following Canvas's Link pagination to the end."""
    url = (f"{base}/api/v1/courses/{course}/assignments/{assignment}"
           f"/submissions?include[]=group&include[]=user&per_page=100")
    out = []
    while url:
        page, headers = http_get_json(url, token)
        out.extend(page)
        url = parse_next_link(headers)
    return out


def main():
    ap = argparse.ArgumentParser(
        description="Clear the late flag on waived submissions.")
    ap.add_argument("course_id")
    ap.add_argument("assignment_id")
    ap.add_argument("--base-url", required=True)
    ap.add_argument("--token")
    ap.add_argument("--token-file")
    ap.add_argument("--group", action="append", default=[])
    ap.add_argument("--user", action="append", default=[])
    ap.add_argument("--status", default="none", choices=VALID)
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("-v", "--verbose", action="store_true")
    a = ap.parse_args()

    if not a.group and not a.user:
        sys.exit("name at least one --group or --user; this will not act on "
                 "a whole assignment by accident")

    token = read_token(a)
    base = a.base_url.rstrip("/")
    subs = submissions(base, token, a.course_id, a.assignment_id)
    want_g = {g.lower() for g in a.group}
    want_u = {str(u) for u in a.user}

    targets, skipped = [], 0
    for s in subs:
        gname = ((s.get("group") or {}).get("name") or "")
        uid = str(s.get("user_id"))
        if gname.lower() not in want_g and uid not in want_u:
            continue
        if not s.get("late") and s.get("late_policy_status") != "late":
            skipped += 1
            if a.verbose:
                print(f"  = {gname or uid}: not flagged late, leaving alone")
            continue
        targets.append((s, gname, uid))

    print(f"{len(subs)} submission(s) on the assignment; "
          f"{len(targets)} flagged late in the groups/users named"
          + (f"; {skipped} already fine" if skipped else ""))
    for s, gname, uid in targets:
        who = ((s.get("user") or {}).get("name")) or f"user {uid}"
        print(f"  {'SET' if a.apply else 'would set'} "
              f"late_policy_status={a.status:<9} "
              f"{gname or '(no group)':<12} {who:<28} "
              f"submitted {s.get('submitted_at')} "
              f"late_by={s.get('seconds_late', 0) // 3600}h")

    if not a.apply:
        print("\nDRY RUN -- nothing was sent.  Re-run with --apply to write.")
        return 0

    ok = 0
    for s, gname, uid in targets:
        url = (f"{base}/api/v1/courses/{a.course_id}/assignments/"
               f"{a.assignment_id}/submissions/{uid}")
        try:
            http_put_json(url, token,
                          {"submission": {"late_policy_status": a.status}})
            ok += 1
        except Exception as exc:
            print(f"  [FAIL] {gname or uid}: {exc}", file=sys.stderr)
    print(f"\nset late_policy_status={a.status} on {ok} of {len(targets)} "
          f"submission(s)")
    return 0 if ok == len(targets) else 1


if __name__ == "__main__":
    sys.exit(main())
