#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.upload_files.py
# Version:      1.0.0
# Date:         2026-03-18
# Purpose:      Upload or replace files on a Canvas assignment. Supports
#               replacing existing files (by file ID) or uploading new files
#               to a course folder. Can also update assignment points.
#
# Usage:        canvas.api.upload_files.py COURSE_ID ASSIGNMENT_ID FILE [FILE ...]
#                   [--replace FILE_ID:LOCAL_PATH ...]
#                   [--points N]
#                   [--folder-id ID]
#                   [-n, --dry-run] [-v, --verbose] [-h, --help]
#
# Input:        Canvas API token + course_id + assignment_id + local files
# Output:       Progress messages to stdout
#
# Options:
#   --replace ID:PATH       Replace Canvas file ID with local file at PATH
#   --points N              Update assignment point value
#   --folder-id ID          Upload to specific folder (default: assignment folder)
#   -n, --dry-run           Show what would be done without making changes
#   -v, --verbose           Show detailed output
#   -h, --help              Show this help message
#
# Requirements:
#   - Canvas API token in ~/.canvas_token (or via --token/--token-file)
#   - ~/.canvas.api.conf with base_url and token_file
#
# Session:      homework.and.exams
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
import uuid

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from canvas_http import http_get_json, http_put_json
from io_utils import load_profile, read_token


# -- Colors ------------------------------------------------------------------

if sys.stderr.isatty():
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    NC = '\033[0m'
else:
    GREEN = YELLOW = RED = NC = ''


def ok(msg):
    print(f"  {GREEN}ok{NC}  {msg}", file=sys.stderr)


def warn(msg):
    print(f"  {YELLOW}warn{NC} {msg}", file=sys.stderr)


def err(msg):
    print(f"  {RED}err{NC}  {msg}", file=sys.stderr)


# -- File upload -------------------------------------------------------------

def upload_file(base_url, token, course_id, local_path, folder_id,
                on_duplicate="overwrite", verbose=False, dry_run=False):
    """Upload a local file to a Canvas course folder.

    Uses Canvas's 3-step upload flow:
      1. POST to /api/v1/courses/:id/files to get upload URL + params
      2. POST file data to the upload URL
      3. (Optional) Follow redirect to confirm

    Returns the Canvas file metadata dict on success.
    """
    filename = os.path.basename(local_path)
    filesize = os.path.getsize(local_path)

    if dry_run:
        ok(f"[dry-run] would upload {filename} ({filesize:,} bytes) to folder {folder_id}")
        return {"id": 0, "display_name": filename}

    # Step 1: Notify Canvas
    notify_url = f"{base_url}/api/v1/courses/{course_id}/files"
    notify_body = urllib.parse.urlencode({
        "name": filename,
        "size": filesize,
        "content_type": "application/octet-stream",
        "parent_folder_id": folder_id,
        "on_duplicate": on_duplicate,
    }).encode("utf-8")

    req = urllib.request.Request(notify_url, data=notify_body, method="POST")
    req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req) as resp:
        step1 = json.loads(resp.read().decode("utf-8"))

    upload_url = step1["upload_url"]
    upload_params = step1.get("upload_params", {})
    if verbose:
        print(f"  Upload URL: {upload_url}", file=sys.stderr)

    # Step 2: Upload the file
    boundary = uuid.uuid4().hex
    parts = []
    for k, v in upload_params.items():
        parts.append(
            f"--{boundary}\r\n"
            f"Content-Disposition: form-data; name=\"{k}\"\r\n\r\n"
            f"{v}\r\n".encode("utf-8")
        )
    with open(local_path, "rb") as f:
        file_data = f.read()
    parts.append(
        f"--{boundary}\r\n"
        f"Content-Disposition: form-data; name=\"file\"; filename=\"{filename}\"\r\n"
        f"Content-Type: application/octet-stream\r\n\r\n".encode("utf-8")
    )
    parts.append(file_data)
    parts.append(f"\r\n--{boundary}--\r\n".encode("utf-8"))
    body = b"".join(parts)

    req = urllib.request.Request(upload_url, data=body, method="POST")
    req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")

    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        if e.code in (301, 303):
            # Follow redirect to confirm upload
            loc = e.headers.get("Location")
            req2 = urllib.request.Request(loc, method="POST")
            req2.add_header("Authorization", f"Bearer {token}")
            with urllib.request.urlopen(req2) as resp2:
                result = json.loads(resp2.read().decode("utf-8"))
        else:
            raise

    ok(f"uploaded {result.get('display_name', filename)} "
       f"(id={result.get('id', '?')}, {filesize:,} bytes)")
    return result


def replace_file(base_url, token, course_id, old_file_id, local_path,
                 verbose=False, dry_run=False):
    """Replace an existing Canvas file by uploading to its folder."""
    # Get old file's folder
    old_file, _ = http_get_json(
        f"{base_url}/api/v1/courses/{course_id}/files/{old_file_id}", token)
    folder_id = old_file["folder_id"]

    if verbose:
        print(f"  Replacing: {old_file['display_name']} "
              f"(id={old_file_id}, folder={folder_id})", file=sys.stderr)

    return upload_file(base_url, token, course_id, local_path, folder_id,
                       on_duplicate="overwrite", verbose=verbose,
                       dry_run=dry_run)


def update_points(base_url, token, course_id, assignment_id, points,
                  verbose=False, dry_run=False):
    """Update an assignment's point value."""
    if dry_run:
        ok(f"[dry-run] would update assignment {assignment_id} points to {points}")
        return

    result, _ = http_put_json(
        f"{base_url}/api/v1/courses/{course_id}/assignments/{assignment_id}",
        token,
        {"assignment": {"points_possible": points}}
    )
    ok(f"points updated to {result['points_possible']}")


# -- CLI ---------------------------------------------------------------------

def parse_replace_arg(s):
    """Parse 'FILE_ID:LOCAL_PATH' into (int, str)."""
    parts = s.split(":", 1)
    if len(parts) != 2:
        raise argparse.ArgumentTypeError(
            f"expected FILE_ID:LOCAL_PATH, got '{s}'")
    try:
        file_id = int(parts[0])
    except ValueError:
        raise argparse.ArgumentTypeError(
            f"FILE_ID must be an integer, got '{parts[0]}'")
    path = parts[1]
    if not os.path.isfile(path):
        raise argparse.ArgumentTypeError(f"file not found: {path}")
    return file_id, path


def main():
    parser = argparse.ArgumentParser(
        description="Upload or replace files on a Canvas assignment.")
    parser.add_argument("course_id", type=int, help="Canvas course ID")
    parser.add_argument("assignment_id", type=int, help="Canvas assignment ID")
    parser.add_argument("--replace", type=parse_replace_arg, action="append",
                        metavar="FILE_ID:LOCAL_PATH",
                        help="Replace Canvas file ID with local file "
                             "(repeatable)")
    parser.add_argument("--points", type=float,
                        help="Update assignment point value")
    parser.add_argument("--base-url", help="Canvas instance URL")
    parser.add_argument("--token", help="Canvas API token (inline)")
    parser.add_argument("--token-file", help="Path to token file")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="Show what would be done without making changes")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Show detailed output")

    args = parser.parse_args()

    profile = load_profile()
    base_url = args.base_url or profile.get("base_url")
    token = read_token(args.token, args.token_file, profile)

    if not base_url:
        err("no base_url: pass --base-url or set in ~/.canvas.api.conf")
        sys.exit(1)

    # Replace files
    if args.replace:
        for old_id, local_path in args.replace:
            replace_file(base_url, token, args.course_id,
                         old_id, local_path,
                         verbose=args.verbose, dry_run=args.dry_run)

    # Update points
    if args.points is not None:
        update_points(base_url, token, args.course_id, args.assignment_id,
                      args.points, verbose=args.verbose, dry_run=args.dry_run)

    if not args.replace and args.points is None:
        warn("nothing to do (specify --replace and/or --points)")


if __name__ == "__main__":
    main()
