#!/usr/bin/env python3
#
# Date: 2026-03-18
# Version: 1.0.0
# Purpose: Stdlib-only HTML-to-Markdown converter targeting Canvas LMS HTML
#          patterns. Used by page download and discussion export scripts.
# Usage: Imported by CLI scripts.
# Input: HTML string (Canvas page body, discussion entry message, etc.)
# Output: Markdown string.
#
# Session:      Canvas.API Infrastructure
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6

import re
from html import unescape
from html.parser import HTMLParser


class _MarkdownConverter(HTMLParser):
    """HTMLParser subclass that accumulates Markdown output."""

    def __init__(self):
        super().__init__(convert_charrefs=False)
        self._out = []          # output fragments
        self._tag_stack = []    # open tag names (with decoration info)
        self._list_stack = []   # 'ul' or 'ol' nesting
        self._ol_counters = []  # current <ol> item number per nesting level
        self._href = None       # current <a> href
        self._in_table = False
        self._table_rows = []   # list of rows, each row is list of cell strings
        self._current_row = []
        self._current_cell = []

    # -- helpers --

    def _push(self, text):
        if self._in_table and self._current_row is not None:
            self._current_cell.append(text)
        else:
            self._out.append(text)

    def _list_indent(self):
        depth = max(0, len(self._list_stack) - 1)
        return "  " * depth

    # -- tag handlers --

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        attrs_dict = dict(attrs)

        # Track underline spans so </span> knows to close with _
        is_underline = (tag == "u" or
                        (tag == "span" and
                         "underline" in attrs_dict.get("style", "")))
        self._tag_stack.append((tag, is_underline))

        if tag in ("p", "div"):
            self._push("\n\n")
        elif tag == "br":
            self._push("\n")
        elif tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            level = int(tag[1])
            self._push("\n\n" + "#" * level + " ")
        elif tag in ("strong", "b"):
            self._push("**")
        elif tag in ("em", "i"):
            self._push("*")
        elif is_underline:
            self._push("_")
        elif tag == "a":
            self._href = attrs_dict.get("href")
            self._push("[")
        elif tag == "img":
            alt = attrs_dict.get("alt", "")
            src = attrs_dict.get("src", "")
            self._push(f"![{alt}]({src})")
        elif tag == "ul":
            self._list_stack.append("ul")
            self._push("\n")
        elif tag == "ol":
            self._list_stack.append("ol")
            self._ol_counters.append(0)
            self._push("\n")
        elif tag == "li":
            if self._list_stack and self._list_stack[-1] == "ol":
                self._ol_counters[-1] = self._ol_counters[-1] + 1
                self._push(f"{self._list_indent()}{self._ol_counters[-1]}. ")
            else:
                self._push(f"{self._list_indent()}- ")
        elif tag == "table":
            self._in_table = True
            self._table_rows = []
        elif tag == "tr":
            self._current_row = []
        elif tag in ("td", "th"):
            self._current_cell = []
        elif tag == "blockquote":
            self._push("\n\n> ")
        elif tag == "code":
            self._push("`")
        elif tag == "pre":
            self._push("\n\n```\n")
        elif tag == "hr":
            self._push("\n\n---\n\n")

    def handle_endtag(self, tag):
        tag = tag.lower()
        # Pop tag stack (tolerant of mismatches); recover underline flag
        is_underline = False
        if self._tag_stack and self._tag_stack[-1][0] == tag:
            _, is_underline = self._tag_stack.pop()

        if tag in ("p", "div"):
            self._push("\n\n")
        elif tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            self._push("\n\n")
        elif tag in ("strong", "b"):
            self._push("**")
        elif tag in ("em", "i"):
            self._push("*")
        elif is_underline:
            self._push("_")
        elif tag == "a":
            if self._href:
                self._push(f"]({self._href})")
            else:
                self._push("]")
            self._href = None
        elif tag == "ul":
            if self._list_stack and self._list_stack[-1] == "ul":
                self._list_stack.pop()
            self._push("\n")
        elif tag == "ol":
            if self._list_stack and self._list_stack[-1] == "ol":
                self._list_stack.pop()
            if self._ol_counters:
                self._ol_counters.pop()
            self._push("\n")
        elif tag == "li":
            self._push("\n")
        elif tag == "table":
            self._in_table = False
            self._flush_table()
        elif tag == "tr":
            if self._current_row is not None:
                self._table_rows.append(self._current_row)
            self._current_row = None
        elif tag in ("td", "th"):
            cell_text = "".join(self._current_cell).strip()
            if self._current_row is not None:
                self._current_row.append(cell_text)
            self._current_cell = []
        elif tag == "blockquote":
            self._push("\n\n")
        elif tag == "code":
            self._push("`")
        elif tag == "pre":
            self._push("\n```\n\n")
        # span: underline spans already handled via is_underline above

    def handle_data(self, data):
        self._push(data)

    def handle_entityref(self, name):
        self._push(unescape(f"&{name};"))

    def handle_charref(self, name):
        self._push(unescape(f"&#{name};"))

    def _flush_table(self):
        """Convert accumulated table rows to a pipe-delimited markdown table."""
        if not self._table_rows:
            return
        # Determine column count from widest row
        ncols = max(len(r) for r in self._table_rows)
        # Pad short rows
        for row in self._table_rows:
            while len(row) < ncols:
                row.append("")
        # Column widths (minimum 3 for separator)
        widths = [3] * ncols
        for row in self._table_rows:
            for i, cell in enumerate(row):
                widths[i] = max(widths[i], len(cell))

        lines = []
        for ri, row in enumerate(self._table_rows):
            cells = [cell.ljust(widths[i]) for i, cell in enumerate(row)]
            lines.append("| " + " | ".join(cells) + " |")
            # Add separator after header row
            if ri == 0:
                sep = ["-" * widths[i] for i in range(ncols)]
                lines.append("| " + " | ".join(sep) + " |")
        self._push("\n\n" + "\n".join(lines) + "\n\n")

    def get_result(self):
        text = "".join(self._out)
        # Normalize whitespace: collapse 3+ newlines to 2
        text = re.sub(r'\n{3,}', '\n\n', text)
        # Remove non-breaking spaces
        text = text.replace('\u00a0', ' ')
        # Remove lines that are only whitespace (from &nbsp;-only paragraphs)
        text = re.sub(r'\n[ \t]+\n', '\n\n', text)
        # Strip leading/trailing whitespace
        return text.strip()


def html_to_markdown(html_string):
    """Convert Canvas HTML to readable Markdown.

    Handles: <p>, <h1>-<h6>, <a href>, <ul>/<ol>/<li>,
    <strong>/<b>, <em>/<i>, <u>, <br>, <img>, <table>,
    <blockquote>, <code>, <pre>, <hr>, HTML entities.

    Returns a Markdown string.
    """
    if not html_string:
        return ""
    converter = _MarkdownConverter()
    converter.feed(html_string)
    return converter.get_result()


def strip_html(html_string):
    """Remove all HTML tags, returning plain text with entities decoded."""
    if not html_string:
        return ""
    # Remove tags
    text = re.sub(r'<[^>]+>', ' ', html_string)
    # Decode entities
    text = unescape(text)
    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text)
    return text.strip()
