#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.download_pages.py
# Version:      1.0.0
# Date:         2026-03-18
# Purpose:      Download Canvas session pages, saving raw HTML, converted
#               Markdown, and JSON metadata per page.
#
# Usage:        canvas.api.download_pages.py COURSE_ID
#                   [--session PREFIX] [--outdir DIR]
#                   [--base-url URL] [--token TOKEN | --token-file FILE]
#                   [--update] [--dry-run] [--verbose] [--help]
#
# Input:        Canvas API token + course_id (or ~/.canvas.api.conf)
# Output:       Per-session directories with page.html, page.md, page.json
#
# Options:
#   --session PREFIX       Only download pages matching this prefix (e.g. S12)
#   --outdir DIR           Output directory (default: output/Pages)
#   --base-url URL         Canvas instance URL (or set in ~/.canvas.api.conf)
#   --token TOKEN          Inline API token
#   --token-file FILE      Path to token file (or set in ~/.canvas.api.conf)
#   -u, --update           Skip pages whose output directory exists
#   -n, --dry-run          Show what would be done without making changes
#   -v, --verbose          Show detailed output
#   -h, --help             Show this help message
#
# Requirements:
#   - Python 3.7+
#   - Canvas API token with instructor access to the course
#
# Session:      Canvas.API Infrastructure
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from canvas_api import get_page, get_pages
from canvas_html import html_to_markdown
from io_utils import (
    extract_session_prefix,
    resolve_credentials,
    sanitize_for_filename,
    session_sort_key,
    write_json,
)


def main():
    ap = argparse.ArgumentParser(
        description="Download Canvas session pages as HTML, Markdown, and JSON.")
    ap.add_argument("course_id", type=int,
                    help="Canvas course ID")
    ap.add_argument("--session", default=None, metavar="PREFIX",
                    help="Only download pages matching this session prefix "
                         "(e.g. S12, S06a)")
    ap.add_argument("--outdir",
                    default=os.path.join("output", "Pages"),
                    help="Output directory (default: output/Pages)")
    ap.add_argument("--base-url", default=None,
                    help="Canvas instance URL (or set base_url in "
                         "~/.canvas.api.conf)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None,
                    help="Path to token file (or set in ~/.canvas.api.conf)")
    ap.add_argument("-u", "--update", action="store_true",
                    help="Skip pages whose output directory exists")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show what would be done without making changes")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show detailed output")
    args = ap.parse_args()

    base_url, token = resolve_credentials(args, ap)

    # Fetch page list
    print(f"Fetching pages for course {args.course_id}...")
    pages = get_pages(base_url, token, args.course_id, verbose=args.verbose)

    # Filter to session-prefixed pages
    session_pages = []
    for p in pages:
        prefix = extract_session_prefix(p.get("title", ""))
        if prefix:
            if args.session and prefix != args.session.upper():
                continue
            session_pages.append((prefix, p))

    # Sort by session number
    session_pages.sort(key=lambda pp: session_sort_key(pp[0]))

    if not session_pages:
        print("No session pages found matching filters.")
        return

    print(f"Found {len(session_pages)} session page(s) to process.\n")

    # Dry-run
    if args.dry_run:
        for prefix, p in session_pages:
            title = p.get("title", "(untitled)")
            slug = sanitize_for_filename(title)
            pdir = os.path.join(args.outdir, slug)
            exists = os.path.isdir(pdir)
            skip = "  [exists, would skip]" if (args.update and exists) else ""
            print(f"  [DRY RUN] {prefix}: {title}{skip}")
        return

    # Download each page
    ok_count = 0
    skip_count = 0
    fail_count = 0
    total = len(session_pages)

    for i, (prefix, p_meta) in enumerate(session_pages, 1):
        title = p_meta.get("title", "(untitled)")
        page_url = p_meta["url"]
        slug = sanitize_for_filename(title)
        page_dir = os.path.join(args.outdir, slug)

        counter = f"[{i}/{total}] " if total > 1 else ""
        print(f"{counter}{prefix}: {title}")

        if args.update and os.path.isdir(page_dir):
            print(f"  [SKIP] Already exists: {page_dir}")
            skip_count = skip_count + 1
            continue

        try:
            # Fetch full page body
            full_page = get_page(base_url, token, args.course_id,
                                 page_url, verbose=args.verbose)
            body_html = full_page.get("body") or ""

            os.makedirs(page_dir, exist_ok=True)

            # Write raw HTML
            html_path = os.path.join(page_dir, "page.html")
            with open(html_path, "w", encoding="utf-8") as f:
                f.write(body_html)

            # Write converted Markdown
            md_path = os.path.join(page_dir, "page.md")
            md_content = f"# {title}\n\n{html_to_markdown(body_html)}"
            with open(md_path, "w", encoding="utf-8") as f:
                f.write(md_content)

            # Write page metadata JSON (without the body to keep it small)
            meta_copy = {k: v for k, v in full_page.items() if k != "body"}
            write_json(os.path.join(page_dir, "page.json"), meta_copy)

            if args.verbose:
                print(f"  [INFO] HTML: {len(body_html)} chars, "
                      f"MD: {len(md_content)} chars")
            print(f"  [OK] {page_dir}")
            ok_count = ok_count + 1

        except Exception as e:
            print(f"  [FAIL] {e}", file=sys.stderr)
            fail_count = fail_count + 1

    # Summary
    if total > 1:
        parts = [f"{ok_count} downloaded"]
        if skip_count:
            parts.append(f"{skip_count} skipped")
        if fail_count:
            parts.append(f"{fail_count} failed")
        print(f"\nDone: {', '.join(parts)} (of {total} pages).")


if __name__ == "__main__":
    main()
