#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.curve_exam.py
# Version:      1.0.0
# Date:         2026-05-06
# Purpose:      Curve a Canvas exam by adding a fixed offset so that the mean
#               or median reaches a target percentage, then upload the results
#               as a new assignment column.
#
# Usage:        canvas.api.curve_exam.py COURSE_ID MATCH
#                   --target N [--stat mean|median]
#                   [--output-name NAME] [--group-id ID]
#                   [--base-url URL] [--token TOKEN | --token-file FILE]
#                   [--dry-run] [--verbose] [--help]
#
# Input:        Canvas API token + course_id + assignment name substring
# Output:       New Canvas assignment with curved scores; summary to stdout
#
# Options:
#   COURSE_ID               Canvas numeric course ID
#   MATCH                   Case-insensitive substring to match assignment name
#   --target N              Target percentage 0-100 (required)
#   --stat mean|median      Statistic to bring to target (default: median)
#   --output-name NAME      Name for new curved assignment
#                           (default: "<source name> (Curved)")
#   --group-id ID           Assignment group for new assignment
#                           (default: same as source)
#   --base-url URL          Canvas instance URL
#   --token TOKEN           Inline API token
#   --token-file FILE       Path to token file
#   -n, --dry-run           Show what would be done without making changes
#   -v, --verbose           Show detailed API output
#   -h, --help              Show this help message
#
# Requirements:
#   - canvas_api.py, canvas_http.py, io_utils.py in the same directory
#   - ~/.canvas.api.conf with base_url and token_file
#
# Session:      Exam 2 Curving
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Sonnet 4.6
# ============================================================================

import argparse
import statistics
import sys

from canvas_api import get_assignments, get_assignment_submissions
from canvas_http import http_post_json, http_put_json
from io_utils import load_profile, read_token, resolve_credentials


def find_assignment(base_url, token, course_id, match, verbose=False):
    """Return all assignments whose name contains MATCH (case-insensitive)."""
    assignments = get_assignments(base_url, token, course_id, verbose=verbose)
    needle = match.lower()
    return [a for a in assignments if needle in a.get("name", "").lower()]


def fetch_graded_scores(base_url, token, course_id, assignment_id, verbose=False):
    """Return list of (user_id, score) for all graded submissions."""
    subs = get_assignment_submissions(
        base_url, token, course_id, assignment_id, verbose=verbose)
    return [(s["user_id"], s["score"])
            for s in subs if s.get("score") is not None]


def compute_offset(scores, stat, target_pts):
    """Return the flat offset needed to bring STAT to TARGET_PTS."""
    if stat == "mean":
        current = statistics.mean(scores)
    else:
        current = statistics.median(scores)
    return target_pts - current, current


def apply_curve(graded, offset, cap):
    """Return list of (user_id, curved_score), capping at CAP."""
    return [(uid, min(sc + offset, cap)) for uid, sc in graded]


def print_summary(label, scores, pts_possible):
    mean   = statistics.mean(scores)
    median = statistics.median(scores)
    print(f"  {label}")
    print(f"    N      : {len(scores)}")
    print(f"    Mean   : {mean:.2f} / {pts_possible:.0f}"
          f" = {mean / pts_possible * 100:.1f}%")
    print(f"    Median : {median:.2f} / {pts_possible:.0f}"
          f" = {median / pts_possible * 100:.1f}%")
    print(f"    Min    : {min(scores):.2f}  Max: {max(scores):.2f}")


def create_assignment(base_url, token, course_id, name, pts_possible,
                      group_id, verbose=False):
    url  = f"{base_url}/api/v1/courses/{course_id}/assignments"
    body = {"assignment": {
        "name"                 : name,
        "points_possible"      : pts_possible,
        "assignment_group_id"  : group_id,
        "grading_type"         : "points",
        "submission_types"     : ["none"],
        "published"            : True,
        "omit_from_final_grade": False,
    }}
    if verbose:
        print(f"[POST] {url}")
    result, _ = http_post_json(url, token, body)
    return result


def upload_grade(base_url, token, course_id, assignment_id, user_id, score,
                 verbose=False):
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/assignments/{assignment_id}/submissions/{user_id}")
    body = {"submission": {"posted_grade": str(round(score, 2))}}
    if verbose:
        print(f"[PUT] {url}  score={score:.2f}")
    http_put_json(url, token, body)


def main():
    ap = argparse.ArgumentParser(
        description=(
            "Curve a Canvas exam by adding a flat offset so that the mean or "
            "median reaches a target percentage, then create a new assignment "
            "column with the curved scores."
        )
    )
    ap.add_argument("course_id", type=int,
                    help="Canvas numeric course ID")
    ap.add_argument("match",
                    help="Case-insensitive substring to identify the source "
                         "assignment (e.g. 'Exam II: With Corrections')")

    ap.add_argument("--target", type=float, required=True, metavar="N",
                    help="Target percentage 0-100 (e.g. 78)")
    ap.add_argument("--stat", choices=["mean", "median"], default="median",
                    help="Statistic to bring to --target (default: median)")
    ap.add_argument("--output-name", default=None,
                    help="Name for the new curved assignment "
                         "(default: '<source name> (Curved)')")
    ap.add_argument("--group-id", type=int, default=None,
                    help="Assignment group ID for new assignment "
                         "(default: same as source)")

    ap.add_argument("--base-url", default=None)
    ap.add_argument("--token", default=None)
    ap.add_argument("--token-file", default=None)

    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show what would be done without uploading")
    ap.add_argument("-v", "--verbose", action="store_true")

    args = ap.parse_args()

    if not (0 <= args.target <= 100):
        ap.error("--target must be between 0 and 100")

    profile  = load_profile()
    base_url, token = resolve_credentials(args, ap)

    # --- Find source assignment ---
    matches = find_assignment(base_url, token, args.course_id, args.match,
                              verbose=args.verbose)
    if not matches:
        print(f"No assignment found matching '{args.match}'.")
        sys.exit(1)
    if len(matches) > 1:
        print(f"Multiple assignments match '{args.match}' -- be more specific:")
        for a in matches:
            print(f"  {a['id']:>8}  pts={a['points_possible']}  {a['name']}")
        sys.exit(1)

    source      = matches[0]
    source_id   = source["id"]
    pts_possible = float(source["points_possible"])
    group_id    = args.group_id or source["assignment_group_id"]
    output_name = args.output_name or f"{source['name']} (Curved)"

    print(f"Source assignment : {source['name']}  (id={source_id})")
    print(f"Points possible   : {pts_possible:.0f}")
    print(f"Target statistic  : {args.stat} = {args.target:.1f}%"
          f" ({args.target / 100 * pts_possible:.2f} pts)")
    print(f"Output name       : {output_name}")
    print()

    # --- Fetch scores ---
    graded = fetch_graded_scores(base_url, token, args.course_id, source_id,
                                 verbose=args.verbose)
    if not graded:
        print("No graded submissions found.")
        sys.exit(1)

    raw_scores = [sc for _, sc in graded]
    print("Before curving:")
    print_summary("", raw_scores, pts_possible)
    print()

    # --- Compute and apply offset ---
    target_pts = args.target / 100.0 * pts_possible
    offset, current_stat = compute_offset(raw_scores, args.stat, target_pts)

    print(f"  Current {args.stat}: {current_stat:.2f} pts")
    print(f"  Offset          : {offset:+.2f} pts")

    curved = apply_curve(graded, offset, pts_possible)
    curved_scores = [sc for _, sc in curved]
    n_capped = sum(1 for sc in curved_scores if sc >= pts_possible)
    if n_capped:
        print(f"  Capped at {pts_possible:.0f}   : {n_capped} student(s)")
    print()

    print("After curving:")
    print_summary("", curved_scores, pts_possible)
    print()

    # --- Per-student table ---
    user_names = {}
    subs = get_assignment_submissions(base_url, token, args.course_id,
                                      source_id, verbose=False)
    for s in subs:
        uid  = s["user_id"]
        name = s.get("user", {}).get("sortable_name", str(uid))
        user_names[uid] = name

    print(f"  {'User ID':>8}  {'Raw':>7}  {'Curved':>7}  {'Curved%':>7}  Name")
    print(f"  {'-------':>8}  {'---':>7}  {'------':>7}  {'-------':>7}  ----")
    orig_map = dict(graded)
    for uid, sc in sorted(curved, key=lambda x: x[1]):
        raw  = orig_map[uid]
        name = user_names.get(uid, str(uid))
        cap  = "*" if sc >= pts_possible else " "
        print(f"  {uid:>8}  {raw:>7.1f}  {sc:>7.1f}{cap} {sc/pts_possible*100:>6.1f}%  {name}")
    print()

    if args.dry_run:
        print("[DRY RUN] No changes made.")
        return

    # --- Create new assignment ---
    print(f"Creating '{output_name}'...")
    new_a = create_assignment(base_url, token, args.course_id, output_name,
                              pts_possible, group_id, verbose=args.verbose)
    new_id = new_a["id"]
    print(f"  Created assignment ID: {new_id}")
    print()

    # --- Upload grades ---
    print(f"Uploading {len(curved)} grades...")
    for uid, sc in curved:
        upload_grade(base_url, token, args.course_id, new_id, uid, sc,
                     verbose=args.verbose)
        name = user_names.get(uid, str(uid))
        print(f"  {uid}  {orig_map[uid]:.1f} -> {sc:.1f}  {name}")

    print()
    print(f"Done.")
    print(f"Assignment URL: {base_url}/courses/{args.course_id}"
          f"/assignments/{new_id}")


if __name__ == "__main__":
    main()
