#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.quiz_submission_events.py
# Version:      1.0.0
# Date:         2026-04-22
# Purpose:      Fetch and analyze Canvas quiz submission event logs to support
#               academic integrity review. Reports tab-switch counts, away
#               time, per-question timing, and class-level comparisons.
#
# Usage:        canvas.api.quiz_submission_events.py COURSE_ID [QUIZ_ID]
#                   [--student NAME] [--base-url URL]
#                   [--token TOKEN | --token-file FILE]
#                   [-v] [-n] [-h]
#
# Input:        Canvas API token + course_id (or ~/.canvas.api.conf)
# Output:       Per-student event summary to stdout
#
# Verbosity:
#   (default)   One summary line per student + any flags
#   -v          Adds full event timeline
#
# Options:
#   --student NAME_OR_NETID Filter to student by NetID (exact) or name substring
#   --base-url URL          Canvas instance URL (or set in ~/.canvas.api.conf)
#   --token TOKEN           Inline API token
#   --token-file FILE       Path to token file (or set in ~/.canvas.api.conf)
#   -n, --dry-run           List submissions that would be fetched, no API calls
#   -v, --verbose           Show full per-student event timeline
#   -h, --help              Show this help message
#
# Notes:
#   Canvas logs page_blurred/page_focused events when a student switches
#   browser tabs during a quiz. Zero tab switches on a quiz with essay
#   questions is notable but not proof of misconduct: a student could use
#   a native LLM app, a separate device, or simply know the material.
#   The events endpoint requires instructor/teacher role.
#
# Session:      Cancer-Evolution-LLM-Integrity
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Sonnet 4.6
# ============================================================================

import argparse
import re
import sys
from datetime import datetime

from canvas_api import (
    get_quiz,
    get_quiz_questions,
    get_quiz_submission_data,
    get_quiz_submission_events,
    get_quiz_submissions,
    get_quizzes,
)
from io_utils import load_profile, read_token


# ---- Helpers ----

def parse_ts(s):
    """Parse ISO 8601 timestamp string to datetime (UTC-aware)."""
    if not s:
        return None
    s = s.replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(s)
    except ValueError:
        return None


def event_ts(evt):
    """Extract timestamp from a Canvas event dict.

    Canvas returns 'created_at' (not 'client_timestamp') for quiz events.
    """
    return parse_ts(evt.get("created_at") or evt.get("client_timestamp"))


def fmt_elapsed(total_seconds):
    """Format seconds-from-start as M:SS."""
    if total_seconds is None or total_seconds < 0:
        return "?"
    s = int(total_seconds)
    return f"{s // 60}:{s % 60:02d}"


def fmt_duration(seconds):
    """Format a duration for display: '4m 23s', '1h 2m', '0s'."""
    if seconds is None:
        return "?"
    s = int(seconds)
    if s < 60:
        return f"{s}s"
    if s < 3600:
        m, sec = divmod(s, 60)
        return f"{m}m {sec:02d}s" if sec else f"{m}m"
    h, rem = divmod(s, 3600)
    m = rem // 60
    return f"{h}h {m}m" if m else f"{h}h"


def strip_html(text):
    """Remove HTML tags and decode common entities."""
    if not text:
        return ""
    text = re.sub(r"<[^>]+>", " ", str(text))
    text = re.sub(r"&nbsp;", " ", text)
    text = re.sub(r"&amp;", "&", text)
    text = re.sub(r"&lt;", "<", text)
    text = re.sub(r"&gt;", ">", text)
    text = re.sub(r"&#\d+;", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def word_count(text):
    """Count words in text (HTML stripped)."""
    text = strip_html(text)
    return len(text.split()) if text else 0


def median(values):
    """Return median of a non-empty list, or None."""
    if not values:
        return None
    s = sorted(values)
    n = len(s)
    return s[n // 2] if n % 2 == 1 else (s[n // 2 - 1] + s[n // 2]) / 2.0


ESSAY_TYPES = {"essay_question", "short_answer_question"}


# ---- Event analysis ----

def analyze_events(events, question_meta):
    """Parse a raw Canvas event list into a structured summary.

    Returns a dict:
      tab_switches      int   -- count of page_blurred events
      away_time_sec     float -- total seconds spent with tab blurred
      away_episodes     list of (blurred_dt, focused_dt, duration_sec)
      answer_events     list of answer dicts (see below)
      answer_revisions  dict of q_id -> int (how many times answered)
      session_start     datetime or None
      raw_events        sorted raw event list

    Each answer dict:
      ts, elapsed_from_start_sec, elapsed_from_prev_sec,
      q_id, q_pos, q_type, answer_text, word_count, revision_num
    """
    # Canvas returns created_at; sort by it (falls back gracefully if absent)
    sorted_evts = sorted(events, key=lambda e: e.get("created_at") or e.get("client_timestamp") or "")

    tab_switches = 0
    away_episodes = []
    last_blurred_ts = None
    session_start = None

    # Track per-question answer count for revision numbering and word-count deltas
    answer_revision_count = {}
    prev_word_count = {}
    answer_events = []

    prev_ts = None
    for evt in sorted_evts:
        ts = event_ts(evt)
        etype = evt.get("event_type", "")
        edata = evt.get("event_data")

        if etype == "session_started":
            if session_start is None:
                session_start = ts

        elif etype == "page_blurred":
            tab_switches += 1
            last_blurred_ts = ts

        elif etype == "page_focused":
            if last_blurred_ts and ts:
                dur = (ts - last_blurred_ts).total_seconds()
                away_episodes.append((last_blurred_ts, ts, dur))
            last_blurred_ts = None

        elif etype in ("question_viewed", "submission_created"):
            pass  # informational only; not used in current analysis

        elif etype == "question_answered":
            answers = edata if isinstance(edata, list) else []
            for ans in answers:
                # Canvas returns quiz_question_id as a string in event_data
                qid_raw = ans.get("quiz_question_id")
                try:
                    qid = int(qid_raw)
                except (TypeError, ValueError):
                    qid = qid_raw
                meta = question_meta.get(qid, {})
                answer_val = ans.get("answer", "")
                # Essays are strings; MC answers are IDs or lists
                if isinstance(answer_val, str):
                    answer_text = answer_val
                else:
                    answer_text = ""

                rev = answer_revision_count.get(qid, 0) + 1
                answer_revision_count[qid] = rev

                elapsed_start = None
                if ts and session_start:
                    elapsed_start = (ts - session_start).total_seconds()
                elapsed_prev = None
                if ts and prev_ts:
                    elapsed_prev = (ts - prev_ts).total_seconds()

                wc = word_count(answer_text)
                prev_wc = prev_word_count.get(qid, 0)
                delta_words = wc - prev_wc
                prev_word_count[qid] = wc

                answer_events.append({
                    "ts": ts,
                    "elapsed_from_start_sec": elapsed_start,
                    "elapsed_from_prev_sec": elapsed_prev,
                    "q_id": qid,
                    "q_pos": meta.get("position"),
                    "q_type": meta.get("question_type", "unknown"),
                    "answer_text": answer_text,
                    "word_count": wc,
                    "delta_words": delta_words,
                    "revision_num": rev,
                })

        if ts:
            prev_ts = ts

    away_time_sec = sum(d for _, _, d in away_episodes)

    return {
        "tab_switches": tab_switches,
        "away_time_sec": away_time_sec,
        "away_episodes": away_episodes,
        "answer_events": answer_events,
        "answer_revisions": answer_revision_count,
        "session_start": session_start,
        "raw_events": sorted_evts,
    }


# ---- Output ----

def _flags(analysis, time_spent_sec, class_median_wpm):
    """Return list of flag strings for this submission.

    Paste detection: a sudden large word-count jump in a single save event
    is the key signal.  Normal typing at 80 WPM adds ~1.3 words/sec; a jump
    of 25+ words in under 10 seconds (>2.5 w/s) is very unlikely to be typing.
    Threshold: delta_words >= 25 AND rate > 2.5 words/sec (or elapsed == 0).
    """
    flags = []

    essay_answers = [a for a in analysis["answer_events"]
                     if a["q_type"] in ESSAY_TYPES]
    essay_q_ids = {a["q_id"] for a in essay_answers}
    tab_count = analysis["tab_switches"]

    # Zero tab switches with essay questions
    if tab_count == 0 and essay_q_ids:
        flags.append(
            f"[!] Zero tab switches on a quiz with {len(essay_q_ids)} "
            f"essay question(s). Student never switched browser tabs."
        )

    # Essay WPM outlier vs class
    if class_median_wpm and time_spent_sec:
        last_essay_by_q = {}
        for a in essay_answers:
            last_essay_by_q[a["q_id"]] = a
        total_essay_words = sum(a["word_count"] for a in last_essay_by_q.values())
        time_min = time_spent_sec / 60.0
        if time_min > 0:
            wpm = total_essay_words / time_min
            if class_median_wpm > 0 and wpm > 2 * class_median_wpm:
                flags.append(
                    f"[!] Essay WPM ({wpm:.0f}) is >2x class median "
                    f"({class_median_wpm:.0f}). Unusually fast relative to peers."
                )

    # Sudden word-count jumps: consistent with pasting a block of text
    for a in essay_answers:
        delta = a.get("delta_words", 0)
        elap = a.get("elapsed_from_prev_sec")
        if delta < 25:
            continue
        rate = delta / elap if (elap and elap > 0) else float("inf")
        if rate > 2.5:
            pos = a.get("q_pos", "?")
            elap_str = f"{elap:.0f}s" if elap is not None else "?"
            rate_str = f"{rate:.1f}" if rate != float("inf") else "instant"
            flags.append(
                f"[!] Essay Q{pos}: +{delta}w in {elap_str} "
                f"({rate_str} w/s) -- sudden text block, possible paste"
            )

    return flags


def print_student_report(student_name, submission, analysis,
                         class_median_tabs, class_median_wpm,
                         verbose=False):
    """Print event analysis for one student."""
    score = submission.get("score")
    pts_possible = submission.get("_pts_possible")
    time_spent = submission.get("time_spent")

    score_str = (f"{score}/{pts_possible}"
                 if score is not None and pts_possible else
                 (str(score) if score is not None else "?"))
    time_str = fmt_duration(time_spent) if time_spent else "?"

    tab_count = analysis["tab_switches"]
    away_sec = analysis["away_time_sec"]

    tab_flag = "  [!]" if (tab_count == 0 and any(
        a["q_type"] in ESSAY_TYPES for a in analysis["answer_events"])) else ""

    # Essay words from last answer per question
    last_essay_by_q = {}
    for a in analysis["answer_events"]:
        if a["q_type"] in ESSAY_TYPES:
            last_essay_by_q[a["q_id"]] = a
    essay_words = sum(a["word_count"] for a in last_essay_by_q.values())

    wpm_str = ""
    if essay_words and time_spent:
        wpm = essay_words / (time_spent / 60.0)
        wpm_str = f"  essay-wpm={wpm:.0f}"

    med_tabs_str = (f"  (class median: {class_median_tabs:.0f})"
                    if class_median_tabs is not None else "")

    print(f"\n  {student_name}")
    print(f"    score={score_str}  time={time_str}  "
          f"tab-switches={tab_count}{tab_flag}{med_tabs_str}  "
          f"away={fmt_duration(int(away_sec))}{wpm_str}")

    if not analysis["raw_events"]:
        print("    (no events logged for this submission)")
    elif verbose:
        _print_timeline(analysis)

    # Print flags
    flags = _flags(analysis, time_spent, class_median_wpm)
    for f in flags:
        for line in f.split("\n"):
            print(f"    {line}")


def _print_timeline(analysis):
    """Print full event timeline indented under the student entry."""
    start = analysis["session_start"]
    print(f"\n    {'Elapsed':<9} {'Event':<22} {'Detail'}")
    print(f"    {'-'*9} {'-'*22} {'-'*35}")

    for evt in analysis["raw_events"]:
        ts = event_ts(evt)
        etype = evt.get("event_type", "")
        edata = evt.get("event_data")

        elapsed_str = fmt_elapsed((ts - start).total_seconds()) if (ts and start) else "?"

        detail = ""
        if etype == "question_answered" and isinstance(edata, list):
            parts = []
            for ans in edata:
                qid_raw = ans.get("quiz_question_id")
                try:
                    qid = int(qid_raw)
                except (TypeError, ValueError):
                    qid = qid_raw
                # Find matching answer_event for this qid + ts
                match = next(
                    (a for a in analysis["answer_events"]
                     if a["q_id"] == qid and a["ts"] == ts),
                    None
                )
                if match:
                    pos = match.get("q_pos", "?")
                    qtype = match["q_type"]
                    short_type = (qtype.replace("_question", "")
                                  .replace("multiple_choice", "mc")
                                  .replace("short_answer", "sa")
                                  .replace("true_false", "tf"))
                    wc = match["word_count"]
                    elap_prev = match.get("elapsed_from_prev_sec")
                    rev = match["revision_num"]
                    rev_str = f" (rev {rev})" if rev > 1 else ""
                    time_str = (f" +{fmt_elapsed(elap_prev)}"
                                if elap_prev is not None else "")
                    wc_str = f" {wc}w" if wc > 0 else ""
                    delta = match.get("delta_words", 0)
                    delta_str = f" [+{delta}w]" if delta >= 25 else ""
                    parts.append(f"Q{pos} ({short_type}){rev_str}{time_str}{wc_str}{delta_str}")
                else:
                    parts.append(f"Q? (id={qid})")
            detail = "; ".join(parts)

        elif etype == "page_focused":
            # Find matching away episode
            ep = next(
                (ep for ep in analysis["away_episodes"] if ep[1] == ts),
                None
            )
            if ep:
                detail = f"(away {fmt_duration(int(ep[2]))})"

        print(f"    {elapsed_str:<9} {etype:<22} {detail}")

    print()


# ---- Per-quiz logic ----

def _compute_class_wpm(all_sub_data):
    """Compute class median essay WPM from (submission, analysis) pairs."""
    wpms = []
    for sub, analysis in all_sub_data:
        time_spent = sub.get("time_spent") or 0
        if not time_spent:
            continue
        last_essay_by_q = {}
        for a in analysis["answer_events"]:
            if a["q_type"] in ESSAY_TYPES:
                last_essay_by_q[a["q_id"]] = a
        total_words = sum(a["word_count"] for a in last_essay_by_q.values())
        if total_words:
            wpms.append(total_words / (time_spent / 60.0))
    return median(wpms)


def process_quiz(base_url, token, course_id, quiz, student_filter,
                 verbose=False, dry_run=False):
    """Fetch events for all (filtered) submissions of one quiz and report."""
    qid = quiz["id"]
    title = quiz.get("title", "(untitled)")
    pts_possible = quiz.get("points_possible", 0)

    print(f"\n{'='*70}")
    print(f"Quiz: {title}  (ID: {qid})")
    print(f"{'='*70}")

    # Fetch submissions
    quiz_subs = get_quiz_submissions(base_url, token, course_id, qid)
    if not quiz_subs:
        print("  No submissions found.")
        return

    # Build user_id -> sortable name and login_id (NetID) from assignment submissions
    user_names = {}
    user_netids = {}
    assignment_id = quiz.get("assignment_id")
    if assignment_id:
        assign_subs = get_quiz_submission_data(
            base_url, token, course_id, assignment_id)
        for asub in assign_subs:
            uid = asub.get("user_id")
            user_obj = asub.get("user")
            if user_obj and isinstance(user_obj, dict):
                user_names[uid] = (user_obj.get("sortable_name")
                                   or user_obj.get("name")
                                   or str(uid))
                login = user_obj.get("login_id", "")
                if login:
                    user_netids[uid] = login

    # Question metadata: id -> {position, question_type}
    qq_list = get_quiz_questions(base_url, token, course_id, qid)
    question_meta = {q["id"]: q for q in qq_list}

    # Determine which submissions to show (match name substring OR exact NetID)
    def name_matches(uid):
        if not student_filter:
            return True
        f = student_filter.lower()
        name = user_names.get(uid, "").lower()
        netid = user_netids.get(uid, "").lower()
        return f in name or f == netid

    show_subs = [s for s in quiz_subs if name_matches(s.get("user_id"))]

    if not show_subs:
        print(f"  No submissions match --student '{student_filter}'.")
        return

    total = len(quiz_subs)
    shown = len(show_subs)
    print(f"  Submissions: {total} total, {shown} shown")

    if dry_run:
        for qs in show_subs:
            uid = qs.get("user_id")
            name = user_names.get(uid, str(uid))
            netid = user_netids.get(uid, "")
            netid_str = f" ({netid})" if netid else ""
            print(f"  [DRY RUN] {name}{netid_str}  "
                  f"(quiz_submission_id={qs.get('id')})")
        return

    # Fetch events for ALL submissions (needed for class-wide stats)
    all_sub_data = []
    for qs in quiz_subs:
        sid = qs.get("id")
        events = get_quiz_submission_events(
            base_url, token, course_id, qid, sid, verbose=verbose)
        analysis = analyze_events(events, question_meta)
        all_sub_data.append((qs, analysis))

    # Class-level stats
    all_tab_counts = [a["tab_switches"] for _, a in all_sub_data]
    all_away_times = [a["away_time_sec"] for _, a in all_sub_data]
    class_med_tabs = median(all_tab_counts)
    class_med_away = median(all_away_times)
    class_med_wpm = _compute_class_wpm(all_sub_data)

    wpm_str = f"  median-essay-wpm={class_med_wpm:.0f}" if class_med_wpm else ""
    print(f"  Class medians: tab-switches={class_med_tabs:.0f}"
          f"  away-time={fmt_duration(int(class_med_away or 0))}{wpm_str}")

    # Print report for filtered students
    show_ids = {s.get("user_id") for s in show_subs}
    for qs, analysis in all_sub_data:
        uid = qs.get("user_id")
        if uid not in show_ids:
            continue
        qs["_pts_possible"] = pts_possible
        name = user_names.get(uid, str(uid))
        netid = user_netids.get(uid, "")
        display_name = f"{name} ({netid})" if netid else name
        print_student_report(display_name, qs, analysis,
                             class_median_tabs=class_med_tabs,
                             class_median_wpm=class_med_wpm,
                             verbose=verbose)


# ---- CLI ----

def main():
    ap = argparse.ArgumentParser(
        description="Fetch and analyze Canvas quiz submission event logs "
                    "for academic integrity review.",
        add_help=True)
    ap.add_argument("course_id", type=int,
                    help="Canvas course ID")
    ap.add_argument("quiz_id", nargs="?", type=int, default=None,
                    help="Canvas quiz ID (omit for all quizzes)")
    ap.add_argument("--student", default=None, metavar="NAME_OR_NETID",
                    help="Filter to student by NetID (exact) or name substring "
                         "(case-insensitive)")
    ap.add_argument("--base-url", default=None, metavar="URL",
                    help="Canvas instance URL (or set in ~/.canvas.api.conf)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None, metavar="FILE",
                    help="Path to token file (or set in ~/.canvas.api.conf)")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="List submissions without fetching events")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show full event timeline per student")

    args = ap.parse_args()

    profile = load_profile()
    if not args.base_url:
        args.base_url = profile.get("base_url")
    if not args.base_url:
        ap.error("--base-url required (or set base_url in ~/.canvas.api.conf)")
    token = read_token(args.token, args.token_file, profile)
    base_url = args.base_url.rstrip("/")

    if args.quiz_id is not None:
        quiz_list = [get_quiz(base_url, token, args.course_id, args.quiz_id)]
    else:
        print(f"Fetching quiz list for course {args.course_id}...")
        all_quizzes = get_quizzes(base_url, token, args.course_id)
        quiz_list = [
            q for q in all_quizzes
            if q.get("published")
            and q.get("quiz_type") not in ("survey", "graded_survey")
        ]
        quiz_list.sort(key=lambda q: q.get("title", ""))

    if not quiz_list:
        print("No quizzes found.")
        sys.exit(0)

    for quiz in quiz_list:
        process_quiz(base_url, token, args.course_id, quiz,
                     student_filter=args.student,
                     verbose=args.verbose,
                     dry_run=args.dry_run)


if __name__ == "__main__":
    main()
