#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.recreate_groups.py
# Version:      1.0.0
# Date:         2026-04-22
# Purpose:      Recreate EEB403 2026 project groups in Canvas group category
#               41711 ("Project Groups") from hardcoded CATME team roster.
#
# Usage:        canvas.api.recreate_groups.py [-n] [-v] [-h]
# Input:        Canvas API token + hardcoded team roster
# Output:       7 groups created with members enrolled
#
# Options:
#   -n, --dry-run   Show what would be done without making changes
#   -v, --verbose   Show detailed output
#   -h, --help      Show this help message
#
# Requirements:
#   - canvas_http, io_utils in same directory
#
# Session:      exam-2-grading
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Sonnet 4.6
# ============================================================================

import argparse
import json
import sys
import urllib.request
import urllib.error

from io_utils import load_profile, read_token

GROUP_CATEGORY_ID = 41711

# Canvas user IDs from 2026-04-08 grades export + CATME II/III rosters
# Terrones excluded from POGs (dropped per CATME III)
TEAMS = {
    "Drifters": [274847, 261883, 248726, 378850],    # Jaeger, Koziol, Pence, Sweeney
    "Elements": [264388, 359914, 265749, 275866],    # Daniels, Natale, Sexton, Taylor
    "Factors":  [286673, 258433, 306091, 244506, 313895],  # Arntz, Davenport, Hargis, Saeed, Smith
    "POGs":     [322622, 280952, 265995, 350906],    # Etienne, Rameshkumar, Rochford, Wilhelmi
    "TSGs":     [268633, 332443, 330606, 386969],    # Ayers, Novak, Sra, Walsh
    "Variants": [372614, 306171, 305366, 192841],    # Dyar, Gammill, Mancarella, Seo
    "Wildtype": [306776, 313837, 272068, 336859],    # Malloy, McAlees, Meletiou, Rodriguez Gomez
}


def api_post(url, token, data, dry_run=False, verbose=False):
    if dry_run:
        if verbose:
            print(f"  [DRY RUN] POST {url}")
            print(f"            {json.dumps(data)}")
        return {"id": 0, "name": data.get("name", "?")}
    body = json.dumps(data).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        print(f"  ERROR {e.code} {e.reason}: {e.read().decode()[:200]}", file=sys.stderr)
        return None


def main():
    parser = argparse.ArgumentParser(
        description="Recreate EEB403 2026 Canvas project groups from CATME roster."
    )
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="Show what would be done without making changes")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Show detailed output")
    args = parser.parse_args()

    profile = load_profile()
    base = profile["base_url"]
    token = read_token(None, profile.get("token_file", "~/.canvas_token"))

    total_groups = 0
    total_members = 0

    for team_name, user_ids in sorted(TEAMS.items()):
        print(f"\n[{team_name}] Creating group ({len(user_ids)} members)...")

        # Create the group
        group = api_post(
            f"{base}/api/v1/group_categories/{GROUP_CATEGORY_ID}/groups",
            token,
            {"name": team_name, "join_level": "invitation_only"},
            dry_run=args.dry_run,
            verbose=args.verbose,
        )
        if group is None:
            print(f"  FAILED to create group {team_name}", file=sys.stderr)
            continue

        group_id = group["id"]
        if not args.dry_run:
            print(f"  Created group ID {group_id}")
        total_groups += 1

        # Add members
        for uid in user_ids:
            result = api_post(
                f"{base}/api/v1/groups/{group_id}/memberships",
                token,
                {"user_id": uid},
                dry_run=args.dry_run,
                verbose=args.verbose,
            )
            if result is None:
                print(f"  FAILED to add user {uid}", file=sys.stderr)
            else:
                if args.verbose or args.dry_run:
                    print(f"  {'[DRY RUN] ' if args.dry_run else ''}Added user {uid}")
                total_members += 1

    print(f"\nDone. {total_groups} groups, {total_members} memberships"
          f"{' (dry run)' if args.dry_run else ''}.")


if __name__ == "__main__":
    main()
