#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.browser.py
# Version:      1.1.0
# Date:         2026-08-11
# Purpose:      Drive Canvas in a real browser for the things the REST API
#               cannot reach -- LTI tools such as Roll Call (Attendance),
#               whose state lives in the tool's own service and is only
#               visible once the tool has been launched from inside Canvas.
#
# Authentication is the whole difficulty. UTK sits behind SSO + Duo, which
# cannot be scripted and should not be. So this keeps a DEDICATED Playwright
# browser profile at ~/.canvas_browser/: you log in by hand once, headed, and
# every later run reuses it.
#
# The profile DIRECTORY alone is not enough, and assuming it was cost a run:
# Canvas issues `canvas_session` and `_normandy_session` as session cookies,
# which Chromium discards when the browser closes, so a saved profile comes
# back with fourteen cookies and none of them from Canvas. The login is
# actually carried by `state.json` inside the profile, written with
# storage_state(), which serialises session cookies too.
#
# Sessions still expire. Rather than fail with "run login first", a headed
# command re-prompts in the window it already has open and re-saves. Headless
# cannot prompt, so it says so.
#
# The profile is a credential store. It is outside every repository, mode
# 0700, and must never be committed or synced.
#
# This does not replace the API scripts. Anything the REST API can answer
# should be asked of the REST API -- it is faster, scriptable, and does not
# depend on a session. Reach for this only for LTI tools and UI-only settings.
#
# Usage:        canvas.api.browser.py [OPTIONS] COMMAND [ARGS]
#
# Commands:
#   login                 Open headed and wait for you to finish SSO, then
#                         verify and save the session
#   status                Report whether the saved session still authenticates
#   rollcall COURSE_ID    Launch the Attendance (Roll Call) tool in a course,
#                         dump what it shows, and report every assignment the
#                         launch created or changed
#   open URL              Navigate, screenshot, and dump the page text
#
# Input:        ~/.canvas.api.conf for base_url and token_file
#               ~/.canvas_browser/ for the saved browser session
# Output:       Screenshots and text dumps under --outdir
#
# Options:
#   -o, --outdir DIR      Where to write screenshots and dumps
#                         (default: <repo>/output)
#       --profile DIR     Browser profile directory
#                         (default: ~/.canvas_browser)
#       --base-url URL    Canvas base URL (default: from ~/.canvas.api.conf)
#       --token-file FILE Canvas API token, for the assignment diff
#       --headless        Run without a visible window; login never does
#       --timeout SECS    How long to wait for a manual login (default 300)
#       --no-diff         Skip the before/after assignment comparison
#       --settings        rollcall: also capture the tool's settings panel
#   -n, --dry-run         Report what would happen, touch nothing
#   -v, --verbose         Detailed progress
#   -h, --help            Show this help message
#
# Requirements:
#   - python3, playwright  (pip install playwright)
#   - playwright install chromium  +  playwright install-deps chromium
#
# Session:      Claude Code session (Roll Call and the recitation penalty)
# AI Model:     Claude Opus 5
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 5
# ============================================================================

import argparse
import datetime
import json
import os
import sys
import time
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

DEFAULT_PROFILE = os.path.expanduser("~/.canvas_browser")
ROLLCALL_HOST = "rollcall.instructure.com"

# The Attendance tool is installed at the account level; in a course it is
# reached as an external tool by id.  3 is UTK's.
ATTENDANCE_TOOL_ID = 3


class BrowserError(Exception):
    pass


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_profile_config():
    try:
        from io_utils import load_profile
        return load_profile() or {}
    except Exception:
        return {}


def resolve(args):
    cfg = load_profile_config()
    base = args.base_url or cfg.get("base_url")
    if not base:
        raise BrowserError(
            "no base_url: set it in ~/.canvas.api.conf or pass --base-url")
    token_file = args.token_file or cfg.get("token_file") or "~/.canvas_token"
    return base.rstrip("/"), os.path.expanduser(token_file)


def read_token(path):
    try:
        with open(path) as fh:
            return fh.read().strip()
    except OSError:
        return None


def api_get(base, token, path):
    """A plain REST GET, used only for the before/after assignment diff."""
    req = urllib.request.Request(f"{base}/api/v1{path}",
                                 headers={"Authorization": f"Bearer {token}"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def assignment_snapshot(base, token, course_id):
    out = {}
    for a in api_get(base, token,
                     f"/courses/{course_id}/assignments?per_page=200"):
        out[a["id"]] = {
            "name": a["name"],
            "points": a.get("points_possible"),
            "group": a.get("assignment_group_id"),
            "types": tuple(a.get("submission_types") or ()),
            "omit": a.get("omit_from_final_grade"),
            "url": ((a.get("external_tool_tag_attributes") or {})
                    .get("url")),
        }
    return out


def diff_assignments(before, after):
    created = [(i, after[i]) for i in after if i not in before]
    removed = [(i, before[i]) for i in before if i not in after]
    changed = []
    for i in after:
        if i in before and before[i] != after[i]:
            fields = {k: (before[i][k], after[i][k])
                      for k in after[i] if before[i][k] != after[i][k]}
            changed.append((i, after[i]["name"], fields))
    return created, removed, changed


# ---------------------------------------------------------------------------
# Browser
# ---------------------------------------------------------------------------

def ensure_profile(path):
    os.makedirs(path, mode=0o700, exist_ok=True)
    try:
        os.chmod(path, 0o700)
    except OSError:
        pass
    return path


def launch(profile, headless):
    from playwright.sync_api import sync_playwright
    pw = sync_playwright().start()
    ctx = pw.chromium.launch_persistent_context(
        ensure_profile(profile),
        headless=headless,
        viewport={"width": 1440, "height": 900},
        args=["--disable-blink-features=AutomationControlled"],
    )
    return pw, ctx


def state_path(profile):
    return os.path.join(profile, "state.json")


def save_state(ctx, profile):
    """Persist the login.

    A persistent profile directory is NOT enough on its own: Canvas issues
    `canvas_session` and `_normandy_session` as session cookies, which
    Chromium drops when the browser closes.  storage_state() serialises them
    anyway, so it is what actually carries the login between runs.
    """
    ctx.storage_state(path=state_path(profile))
    try:
        os.chmod(state_path(profile), 0o600)
    except OSError:
        pass


def restore_state(ctx, profile, verbose=False):
    p = state_path(profile)
    if not os.path.isfile(p):
        return False
    try:
        with open(p) as fh:
            cookies = json.load(fh).get("cookies") or []
        if cookies:
            ctx.add_cookies(cookies)
        if verbose:
            print(f"  restored {len(cookies)} cookies from {p}")
        return True
    except Exception as exc:
        print(f"warning: could not restore {p}: {exc}", file=sys.stderr)
        return False


def wait_for_login(ctx, base, timeout, verbose=False):
    """Poll until the browser is authenticated, or give up."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        time.sleep(3)
        who = whoami(ctx, base)
        if who:
            return who
    return None


def authenticate(ctx, base, profile, headless, timeout, verbose=False):
    """Get to an authenticated context, re-prompting if the session died.

    Canvas sessions expire, so 'run login again' would be a recurring chore.
    Headed runs just ask; headless runs cannot, and say so.
    """
    restore_state(ctx, profile, verbose)
    who = whoami(ctx, base)
    if who:
        return who
    if headless:
        raise BrowserError(
            "saved session is not authenticated, and --headless cannot "
            "prompt.  Run 'login' first.")
    page = ctx.pages[0] if ctx.pages else ctx.new_page()
    page.goto(base, wait_until="domcontentloaded")
    if whoami(ctx, base):
        save_state(ctx, profile)
        return whoami(ctx, base)
    print(f"session expired -- sign in again in the open window "
          f"(waiting up to {timeout}s) ...")
    who = wait_for_login(ctx, base, timeout)
    if not who:
        raise BrowserError("timed out waiting for sign-in")
    save_state(ctx, profile)
    return who


def whoami(ctx, base):
    """The signed-in user, via a same-origin API call that rides the cookies.

    Returns None when the session is dead, which is the only reliable signal
    -- Canvas answers an unauthenticated page request with a login redirect
    rather than an error.
    """
    try:
        r = ctx.request.get(f"{base}/api/v1/users/self", timeout=20000)
        if not r.ok:
            return None
        d = r.json()
        return d if isinstance(d, dict) and d.get("id") else None
    except Exception:
        return None


def stamp():
    return datetime.datetime.now().strftime("%Y-%m-%dT%H%M%S")


def capture(page, outdir, label, verbose=False):
    """Screenshot plus the text of the page and of every Roll Call frame."""
    os.makedirs(outdir, exist_ok=True)
    base = os.path.join(outdir, f"{stamp()}_{label}")
    png, txt = f"{base}.png", f"{base}.txt"
    page.screenshot(path=png, full_page=True)

    parts = [f"url: {page.url}", f"title: {page.title()}", ""]
    for fr in page.frames:
        try:
            body = fr.locator("body").inner_text(timeout=5000)
        except Exception as exc:
            body = f"<could not read: {type(exc).__name__}>"
        tag = "PAGE" if fr is page.main_frame else f"FRAME {fr.url}"
        parts += [f"--- {tag} ---", body, ""]
    with open(txt, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts))
    if verbose:
        print(f"  captured {png}")
        print(f"           {txt}")
    return png, txt


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_login(args, base, token_file):
    if args.dry_run:
        print(f"would open {base} headed and wait up to {args.timeout}s "
              f"for you to sign in; profile {args.profile}")
        return 0
    pw, ctx = launch(args.profile, headless=False)
    try:
        restore_state(ctx, args.profile, args.verbose)
        page = ctx.pages[0] if ctx.pages else ctx.new_page()
        page.goto(base, wait_until="domcontentloaded")
        who = whoami(ctx, base)
        if who:
            save_state(ctx, args.profile)
            print(f"already signed in as {who.get('name')}")
            return 0
        print(f"Sign in to Canvas in the window that just opened "
              f"(SSO + Duo).\nWaiting up to {args.timeout}s ...")
        who = wait_for_login(ctx, base, args.timeout)
        if not who:
            print("timed out waiting for sign-in", file=sys.stderr)
            return 1
        save_state(ctx, args.profile)
        print(f"signed in as {who.get('name')}")
        print(f"session saved in {state_path(args.profile)}")
        return 0
    finally:
        ctx.close()
        pw.stop()


def cmd_status(args, base, token_file):
    if args.dry_run:
        print(f"would check the saved session in {args.profile} against {base}")
        return 0
    if not os.path.isdir(args.profile):
        print(f"no saved session at {args.profile}; run 'login' first")
        return 1
    pw, ctx = launch(args.profile, headless=True)
    try:
        restore_state(ctx, args.profile, args.verbose)
        who = whoami(ctx, base)
        if who:
            print(f"signed in as {who.get('name')}")
            return 0
        print("saved session is not authenticated; run 'login'")
        return 1
    finally:
        ctx.close()
        pw.stop()


def cmd_rollcall(args, base, token_file):
    course = args.arg
    if not course:
        raise BrowserError("rollcall needs a COURSE_ID")
    url = f"{base}/courses/{course}/external_tools/{ATTENDANCE_TOOL_ID}"

    if args.dry_run:
        print(f"would open {url}\n"
              f"  Launching is non-mutating: Roll Call creates its gradebook "
              f"assignment on the first MARK, not on launch (verified "
              f"2026-08-11, course 261062).")
        return 0

    token = read_token(token_file)
    before = {}
    if token and not args.no_diff:
        before = assignment_snapshot(base, token, course)
        print(f"{len(before)} assignments before launch")
    elif not args.no_diff:
        print(f"no API token at {token_file}; skipping the assignment diff",
              file=sys.stderr)

    pw, ctx = launch(args.profile, headless=args.headless)
    try:
        who = authenticate(ctx, base, args.profile, args.headless,
                           args.timeout, args.verbose)
        print(f"signed in as {who.get('name')}")
        page = ctx.pages[0] if ctx.pages else ctx.new_page()
        print(f"opening {url}")
        page.goto(url, wait_until="domcontentloaded", timeout=60000)

        # The tool renders in an iframe; give it time to hand off.
        found = False
        for _ in range(20):
            if any(ROLLCALL_HOST in f.url for f in page.frames):
                found = True
                break
            page.wait_for_timeout(1000)
        page.wait_for_timeout(3000)
        if found:
            print(f"Roll Call frame loaded")
        else:
            print(f"WARNING: no {ROLLCALL_HOST} frame appeared -- the capture "
                  f"below will show what did", file=sys.stderr)

        png, txt = capture(page, args.outdir, f"rollcall_{course}",
                           args.verbose)
        print(f"screenshot {png}")
        print(f"text       {txt}")

        if args.settings and found:
            # The Late percentage lives only in the tool's own settings
            # panel; there is no API for it.
            # Two clicks, not one: the gear opens a menu whose items
            # ("Roll Call Settings", "Attendance Report") are not clickable
            # until it is open.
            fr = next(f for f in page.frames if ROLLCALL_HOST in f.url)
            for label in ("Settings", "Roll Call Settings"):
                try:
                    fr.get_by_text(label, exact=True).first.click(timeout=5000)
                    page.wait_for_timeout(2500)
                except Exception as exc:
                    print(f"could not click {label!r}: {type(exc).__name__}",
                          file=sys.stderr)
            spng, stxt = capture(page, args.outdir,
                                 f"rollcall_{course}_settings", args.verbose)
            print(f"settings   {spng}")
            print(f"           {stxt}")
    finally:
        ctx.close()
        pw.stop()

    if token and not args.no_diff:
        after = assignment_snapshot(base, token, course)
        created, removed, changed = diff_assignments(before, after)
        print(f"\n{len(after)} assignments after launch")
        if not (created or removed or changed):
            print("  no assignment was created or changed by the launch")
        for i, a in created:
            print(f"  CREATED {i}  {a['name']!r}  {a['points']} pts  "
                  f"group {a['group']}  {a['types']}")
        for i, a in removed:
            print(f"  REMOVED {i}  {a['name']!r}")
        for i, name, fields in changed:
            print(f"  CHANGED {i}  {name!r}")
            for k, (b, a) in fields.items():
                print(f"            {k}: {b!r} -> {a!r}")
    return 0


def cmd_open(args, base, token_file):
    target = args.arg
    if not target:
        raise BrowserError("open needs a URL")
    if "://" not in target:
        target = f"{base}/{target.lstrip('/')}"
    if args.dry_run:
        print(f"would open {target}")
        return 0
    pw, ctx = launch(args.profile, headless=args.headless)
    try:
        authenticate(ctx, base, args.profile, args.headless, args.timeout,
                     args.verbose)
        page = ctx.pages[0] if ctx.pages else ctx.new_page()
        page.goto(target, wait_until="domcontentloaded", timeout=60000)
        page.wait_for_timeout(2000)
        png, txt = capture(page, args.outdir, "page", args.verbose)
        print(f"screenshot {png}")
        print(f"text       {txt}")
        return 0
    finally:
        ctx.close()
        pw.stop()


COMMANDS = {"login": cmd_login, "status": cmd_status,
            "rollcall": cmd_rollcall, "open": cmd_open}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv=None):
    ap = argparse.ArgumentParser(
        description="Drive Canvas in a real browser for what the REST API "
                    "cannot reach.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Commands:\n"
               "  login                 sign in by hand once; the session is "
               "reused afterwards\n"
               "  status                is the saved session still good?\n"
               "  rollcall COURSE_ID    launch Attendance and report what it "
               "created\n"
               "  open URL              navigate, screenshot, dump text\n\n"
               "  canvas.api.browser.py login\n"
               "  canvas.api.browser.py rollcall 261062\n"
               "  canvas.api.browser.py open /courses/261062/assignments\n")
    ap.add_argument("command", choices=sorted(COMMANDS))
    ap.add_argument("arg", nargs="?", help="COURSE_ID or URL, per the command")
    ap.add_argument("-o", "--outdir", default=os.path.join(REPO, "output"),
                    help="where screenshots and dumps go")
    ap.add_argument("--profile", default=DEFAULT_PROFILE,
                    help="browser profile directory")
    ap.add_argument("--base-url", help="Canvas base URL")
    ap.add_argument("--token-file", help="Canvas API token file")
    ap.add_argument("--headless", action="store_true",
                    help="no visible window (login is always headed)")
    ap.add_argument("--timeout", type=int, default=300,
                    help="seconds to wait for a manual login")
    ap.add_argument("--no-diff", action="store_true",
                    help="skip the before/after assignment comparison")
    ap.add_argument("--settings", action="store_true",
                    help="rollcall: also open and capture the tool's settings "
                         "panel, where the Late percentage lives")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="report what would happen, touch nothing")
    ap.add_argument("-v", "--verbose", action="store_true")
    return ap.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    base, token_file = resolve(args)
    if args.verbose:
        print(f"base    {base}")
        print(f"profile {args.profile}")
        print(f"outdir  {args.outdir}")
    return COMMANDS[args.command](args, base, token_file)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BrowserError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        sys.exit(130)
