#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.fetch_gradebook.py
# Version:      1.0.0
# Date:         2026-04-08
# Purpose:      Fetch a Canvas course gradebook via the API and write a CSV
#               in the same column layout as the Canvas UI's gradebook
#               export. Useful when the per-course CSV export is not
#               available via the Reports API and you don't want to
#               download manually from the gradebook UI.
#
# Output CSV layout (matches Canvas gradebook export, minus the
# "Manual Posting" row which is generally not needed downstream):
#   Row 0: Headers ("Student", "ID", "SIS User ID", "SIS Login ID",
#                   "Section", then "<Assignment Name> (<assignment_id>)" ...)
#   Row 1: blank (placeholder for the Manual Posting row)
#   Row 2: "    Points Possible" + per-column points_possible values
#   Row 3+: one row per student
#
# Usage:        canvas.api.fetch_gradebook.py COURSE_ID
#                   [-o OUTPUT_PATH] [--groups GROUP1,GROUP2,...]
#                   [-n] [-v] [-h]
#
# Input:        Canvas API token + course_id
# Output:       Gradebook CSV at OUTPUT_PATH (default:
#               ./<TIMESTAMP>_Grades-COURSE.csv)
#
# Options:
#   -o, --output PATH     CSV output path (default: timestamped file in cwd)
#   --groups NAMES        Comma-separated assignment group names to include
#                         (default: all groups)
#   -n, --dry-run         Show what would be fetched without writing
#   -v, --verbose         Detailed progress output
#   -h, --help            Show this help message
#
# Requirements:
#   - Canvas API token in ~/.canvas_token (or via --token/--token-file)
#   - ~/.canvas.api.conf with base_url and token_file
#
# Session:      student.evaluation
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse
import csv as csvmod
import datetime
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from canvas_api import get_assignment_groups, get_assignments
from canvas_http import paginated_get_all
from io_utils import load_profile, read_token


if sys.stderr.isatty():
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    BLUE = '\033[0;34m'
    NC = '\033[0m'
else:
    GREEN = YELLOW = RED = BLUE = NC = ''


def ok(msg):   print(f"  {GREEN}ok{NC}  {msg}", file=sys.stderr)
def warn(msg): print(f"  {YELLOW}warn{NC} {msg}", file=sys.stderr)
def err(msg):  print(f"  {RED}err{NC}  {msg}", file=sys.stderr)
def info(msg): print(f"  {BLUE}info{NC} {msg}", file=sys.stderr)


def fetch_students(base_url, token, course_id, verbose=False):
    """GET all student-enrollment users for the course."""
    url = (f"{base_url}/api/v1/courses/{course_id}/users"
           f"?enrollment_type[]=student&per_page=100")
    users = paginated_get_all(url, token, verbose=verbose)
    # Drop "Test Student" placeholders
    return [u for u in users if 'Test Student' not in u.get('name', '')]


def fetch_all_submissions(base_url, token, course_id, verbose=False):
    """GET all submissions for all students in the course (one bulk call,
    paginated).
    """
    url = (f"{base_url}/api/v1/courses/{course_id}/students/submissions"
           f"?student_ids[]=all&per_page=100")
    return paginated_get_all(url, token, verbose=verbose)


def main():
    parser = argparse.ArgumentParser(
        description="Fetch a Canvas course gradebook via API and write CSV.")
    parser.add_argument("course_id", type=int, help="Canvas course ID")
    parser.add_argument("-o", "--output",
                        help="CSV output path (default: timestamped file)")
    parser.add_argument("--groups",
                        help="Comma-separated assignment group names to "
                             "include (default: all)")
    parser.add_argument("--base-url", help="Canvas instance URL")
    parser.add_argument("--token", help="Canvas API token (inline)")
    parser.add_argument("--token-file", help="Path to token file")
    parser.add_argument("-n", "--dry-run", action="store_true")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    profile = load_profile()
    base_url = args.base_url or profile.get("base_url")
    token = read_token(args.token, args.token_file, profile)
    if not base_url:
        err("no base_url: pass --base-url or set in ~/.canvas.api.conf")
        sys.exit(1)

    info(f"course {args.course_id}")

    # Fetch metadata
    groups = get_assignment_groups(base_url, token, args.course_id,
                                    verbose=args.verbose)
    group_by_id = {g['id']: g['name'] for g in groups}

    asgns = get_assignments(base_url, token, args.course_id,
                             verbose=args.verbose)
    if args.groups:
        wanted = set(s.strip() for s in args.groups.split(','))
        asgns = [a for a in asgns
                 if group_by_id.get(a['assignment_group_id']) in wanted]
    ok(f"{len(asgns)} assignments across "
       f"{len(set(a['assignment_group_id'] for a in asgns))} groups")

    students = fetch_students(base_url, token, args.course_id,
                              verbose=args.verbose)
    ok(f"{len(students)} students")

    if args.dry_run:
        info("[dry-run] skipping submissions fetch + CSV write")
        return

    info("fetching submissions (bulk)...")
    subs = fetch_all_submissions(base_url, token, args.course_id,
                                  verbose=args.verbose)
    ok(f"{len(subs)} submissions")

    # (user_id, assignment_id) -> score
    matrix = {(s['user_id'], s['assignment_id']): s['score'] for s in subs}

    # Determine output path
    if args.output:
        out_path = args.output
    else:
        ts = datetime.datetime.now().strftime("%Y-%m-%dT%H%M")
        out_path = f"./{ts}_Grades-course{args.course_id}.csv"

    # Sort assignments by id for deterministic output
    ordered = sorted(asgns, key=lambda a: a['id'])
    students.sort(key=lambda u: u.get('sortable_name', u.get('name', '')))

    header = (["Student", "ID", "SIS User ID", "SIS Login ID", "Section"]
              + [f"{a['name']} ({a['id']})" for a in ordered])
    posting_row = [""] * len(header)
    pts_row = (["    Points Possible", "", "", "", ""]
               + [f"{a.get('points_possible') or 0:.2f}" for a in ordered])

    with open(out_path, 'w', newline='') as f:
        w = csvmod.writer(f)
        w.writerow(header)
        w.writerow(posting_row)
        w.writerow(pts_row)
        for u in students:
            row = [
                u.get('sortable_name', u.get('name', '')),
                str(u['id']),
                u.get('sis_user_id', '') or '',
                u.get('login_id', '') or '',
                '',
            ]
            for a in ordered:
                score = matrix.get((u['id'], a['id']))
                row.append(f"{score:.2f}" if score is not None else '')
            w.writerow(row)

    ok(f"wrote {out_path}  ({len(students)} students x {len(ordered)} cols)")


if __name__ == "__main__":
    main()
