#!/usr/bin/env python3
# ============================================================================
# Script:       send_message.py
# Version:      1.0.0
# Created:      2026-09-07
# Revised:      2026-09-07
# Purpose:      Send a Canvas Conversations message to students, groups or staff
#
# Writes a message that recipients see as coming from the authenticated user.
# Intended for course correspondence that should live in Canvas rather than
# email -- submission queries, missing-work notes, group follow-ups.
#
# ALWAYS run with --dry-run first and read the rendered body.  A sent
# conversation cannot be recalled, and it goes out over the token owner's name.
#
# Recipients may be given as bare Canvas user ids, as group_<id> for a whole
# group, or as course_<id> for a whole course.  Resolve names to ids with
# canvas.api.list_courses.py or the /users endpoint before calling this.
#
# Usage:        send_message.py --subject S --body-file F --to ID [--to ID ...]
#                   [--course-id N] [--base-url URL]
#                   [--token TOKEN | --token-file FILE]
#                   [--separate] [--dry-run] [--verbose] [--help]
#
# Input:        Canvas API token; a plain-text file holding the message body
# Output:       Stdout: the rendered message and the resolved recipient list;
#               on send, the created conversation id
#
# Options:
#   --subject S       Message subject (required)
#   --body-file F     File containing the message body (required; use - for stdin)
#   --to ID           Recipient; repeatable. Bare id, group_<id>, or course_<id>
#   --course-id N     Course context, so the message files under that course
#   --separate        Send individual copies instead of one shared thread.
#                     Recipients then cannot see each other (like Bcc).
#   --base-url URL    Canvas instance URL (or base_url in ~/.canvas.api.conf)
#   --token TOKEN     Canvas API token (inline)
#   --token-file FILE Path to token file
#   -n, --dry-run     Render and resolve recipients; send nothing
#   -v, --verbose     Show the API request body
#   -h, --help        Show this help message
#
# Requirements:
#   - Python 3.7+
#   - Canvas API token for the account the message should come from
#
# Session:      HW01.submission.review
# AI Model:     Claude Opus 5
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 5
# ============================================================================

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from canvas_http import http_get_json, http_post_json          # noqa: E402
from io_utils import load_profile, read_token                  # noqa: E402


def _get(base_url, token, path):
    """http_get_json returns (data, headers); we only ever want the data."""
    data, _ = http_get_json(f"{base_url}{path}", token)
    return data


def resolve_recipient(base_url, token, spec, course_id=None, verbose=False):
    """Return (spec, human_label) for a recipient spec, checking it exists.

    Every spec is looked up so a typo fails here rather than silently
    addressing a stranger -- the point of --dry-run is that the printed
    recipient list is the one that will actually receive the message.

    A bare user id is resolved through the COURSE roster, not /users/:id:
    an instructor token has no account-level user read, so /users/:id returns
    404 for a user the instructor can nonetheless message.  Resolving through
    the course also confirms the recipient is actually in this course.
    """
    spec = str(spec).strip()
    try:
        if spec.startswith("group_"):
            gid = spec.split("_", 1)[1]
            g = _get(base_url, token, f"/api/v1/groups/{gid}")
            n = g.get("members_count")
            label = f"group {gid}: {g.get('name')}"
            if n is not None:
                label += f" ({n} members)"
            return spec, label
        if spec.startswith("course_"):
            cid = spec.split("_", 1)[1]
            c = _get(base_url, token, f"/api/v1/courses/{cid}")
            return spec, f"course {cid}: {c.get('name')}"

        uid = int(spec)
        if course_id:
            u = _get(base_url, token,
                     f"/api/v1/courses/{course_id}/users/{uid}"
                     "?include[]=enrollments")
            roles = sorted({e.get("type", "?")
                            for e in (u.get("enrollments") or [])})
            label = f"user {uid}: {u.get('name')}"
            if roles:
                label += f"  [{', '.join(roles)}]"
            return spec, label
        u = _get(base_url, token, f"/api/v1/users/{uid}")
        return spec, f"user {uid}: {u.get('name')}"
    except Exception as e:
        return spec, f"UNRESOLVED ({e})"


def main():
    ap = argparse.ArgumentParser(
        description="Send a Canvas Conversations message. Run --dry-run first: "
                    "a sent conversation cannot be recalled and goes out over "
                    "the token owner's name.")
    ap.add_argument("--subject", required=True, help="Message subject")
    ap.add_argument("--body-file", required=True,
                    help="File holding the message body ('-' for stdin)")
    ap.add_argument("--to", action="append", default=[], required=True,
                    metavar="ID",
                    help="Recipient: user id, group_<id>, or course_<id>; "
                         "repeatable")
    ap.add_argument("--course-id", type=int, default=None,
                    help="Course context for the conversation")
    ap.add_argument("--separate", action="store_true",
                    help="Send individual copies; recipients cannot see each "
                         "other (default is one shared thread)")

    ap.add_argument("--base-url", default=None, help="Canvas instance URL")
    ap.add_argument("--token", default=None, help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None, help="Path to token file")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Render and resolve recipients; send nothing")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show the API request body")
    args = ap.parse_args()

    profile = load_profile()
    base_url = (args.base_url or profile.get("base_url") or "").rstrip("/")
    if not base_url:
        ap.error("--base-url is required (or set base_url in "
                 "~/.canvas.api.conf)")
    token = read_token(args.token, args.token_file, profile)

    if args.body_file == "-":
        body = sys.stdin.read()
    else:
        with open(args.body_file, encoding="utf-8") as fh:
            body = fh.read()
    body = body.rstrip("\n")
    if not body.strip():
        ap.error("message body is empty")

    resolved = [resolve_recipient(base_url, token, s, args.course_id,
                                  args.verbose)
                for s in args.to]

    try:
        me = _get(base_url, token, "/api/v1/users/self/profile")
        sender = f"{me.get('name')} <{me.get('primary_email', '?')}>"
    except Exception as e:
        sender = f"(could not read token owner: {e})"

    rule = "=" * 72
    print(rule)
    print(f"FROM:    {sender}")
    print(f"SUBJECT: {args.subject}")
    print("TO:")
    for spec, label in resolved:
        print(f"    {spec:<16}{label}")
    if args.course_id:
        print(f"CONTEXT: course_{args.course_id}")
    # Reports what is REQUESTED, which is not always what Canvas does: with
    # group_conversation=true and a group_<id> recipient, Canvas was observed
    # to expand the group and create one 2-person conversation per member
    # anyway (BIOL240 F.2026, 5 recipients -> 5 threads).  The send output
    # prints the conversations actually created; trust that, not this line.
    mode = ("individual copies requested (recipients hidden)" if args.separate
            else "shared thread requested -- Canvas may still split it")
    print(f"MODE:    {mode}")
    print(rule)
    print(body)
    print(rule)

    unresolved = [s for s, lbl in resolved if lbl.startswith("UNRESOLVED")]
    if unresolved:
        print(f"\n[ERROR] {len(unresolved)} recipient(s) could not be "
              f"resolved: {', '.join(unresolved)}", file=sys.stderr)
        print("        Nothing was sent. Fix the ids and re-run.",
              file=sys.stderr)
        return 1

    if args.dry_run:
        print("\n[DRY RUN] Nothing was sent.")
        return 0

    payload = {
        "recipients": [s for s, _ in resolved],
        "subject": args.subject,
        "body": body,
        "force_new": True,
        # group_conversation=True puts everyone in one thread so replies reach
        # the whole set; bulk_message=True instead mails separate copies.
        "group_conversation": not args.separate,
        "bulk_message": args.separate,
    }
    if args.course_id:
        payload["context_code"] = f"course_{args.course_id}"
    if args.verbose:
        import json as _json
        print("\n[POST] /api/v1/conversations")
        print(_json.dumps(payload, indent=2))

    try:
        res, _ = http_post_json(f"{base_url}/api/v1/conversations",
                                token, payload)
    except Exception as e:
        print(f"\n[ERROR] send failed: {e}", file=sys.stderr)
        return 1

    convs = res if isinstance(res, list) else [res]
    for c in convs:
        print(f"\n[SENT] conversation {c.get('id')} -- "
              f"{len(c.get('participants') or [])} participant(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
