#!/usr/bin/env python3
#
# Date: 2026-03-18
# Version: 1.4.0
# Purpose: Small IO helpers for reading/writing JSON files, selecting inputs,
#          and loading the user profile (~/.canvas.api.conf).
# Usage: Imported by CLI scripts.
# Input: Paths.
# Output: Python objects or written files.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import configparser
import json
import os
import re


def write_json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=True, indent=2)


def read_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def list_json_files(folder):
    out = []
    for name in sorted(os.listdir(folder)):
        if name.lower().endswith(".json"):
            out.append(os.path.join(folder, name))
    return out


# ---- Filename helpers ----

def sanitize_for_filename(text, max_len=50):
    """Turn a title into a filesystem-safe slug.

    Convention: underscores separate major sections, periods separate
    words within a section.

    Example: "S01: 2025-01-16 - Mutations/Teamwork"
          -> "S01_2025-01-16_Mutations.Teamwork"
    """
    text = text.strip()
    # Section separators (": ", " - ") become underscores
    text = re.sub(r'\s*:\s*', '_', text)
    text = re.sub(r'\s+-\s+', '_', text)
    # Slashes and commas become periods (within-topic separator)
    text = re.sub(r'[/,]+', '.', text)
    # Remaining spaces become periods (words within a section)
    text = re.sub(r'\s+', '.', text)
    # Strip characters unsafe for filenames
    text = re.sub(r'[\\*?"<>|]+', '', text)
    # Collapse runs of underscores or periods
    text = re.sub(r'_+', '_', text)
    text = re.sub(r'\.+', '.', text)
    # Remove trailing underscores/periods
    text = re.sub(r'[_.]+$', '', text)
    # Truncate cleanly
    if len(text) > max_len:
        text = text[:max_len].rstrip('_.')
    return text


# ---- Session prefix utilities ----

def extract_session_prefix(title):
    """Extract session prefix from a Canvas title string.

    Matches patterns like:
        'S12: Topic'       -> 'S12'
        'S06a: Topic'      -> 'S06A'
        'S16-S17: Topic'   -> 'S16-S17'
        'S16-17: Topic'    -> 'S16-17'

    Returns uppercase prefix string, or '' if not found.
    """
    if not title:
        return ""
    m = re.match(r'^(S\d+[a-d]?(?:-S?\d+[a-d]?)?)\s*:', title, re.IGNORECASE)
    return m.group(1).upper() if m else ""


def session_sort_key(prefix):
    """Return (number, letter) sort key for prefixes like 'S12', 'S06a', 'S16-S17'.

    For range prefixes like 'S16-S17', sorts by the first session number.
    """
    if not prefix:
        return (999, "")
    # Handle range prefixes: use first session for sorting
    first = prefix.split("-")[0]
    m = re.match(r'^S(\d+)([a-d]?)$', first, re.IGNORECASE)
    if not m:
        return (999, "")
    return (int(m.group(1)), m.group(2).lower())


# ---- Profile config ----

_PROFILE_PATH = os.path.expanduser("~/.canvas.api.conf")


def load_profile(path=None):
    """Load the user profile from ~/.canvas.api.conf (INI format).

    Returns a dict of key/value pairs from the [default] section.
    Returns an empty dict if the file does not exist.
    Expands ~ in path-like values (token_file).
    """
    path = path or _PROFILE_PATH
    if not os.path.isfile(path):
        return {}
    cp = configparser.ConfigParser()
    cp.read(path, encoding="utf-8")
    if not cp.has_section("default"):
        return {}
    profile = dict(cp.items("default"))
    # Expand ~ in path-like keys
    for key in ("token_file",):
        if key in profile:
            profile[key] = os.path.expanduser(profile[key])
    return profile


def read_token(token, token_file, profile=None):
    """Return a Canvas API token.

    Fallback chain: --token > --token-file > profile token_file > error.
    """
    if token:
        return token.strip()
    if token_file:
        with open(token_file, "r", encoding="utf-8") as f:
            return f.read().strip()
    if profile and profile.get("token_file"):
        with open(profile["token_file"], "r", encoding="utf-8") as f:
            return f.read().strip()
    raise ValueError(
        "No token provided. Use --token, --token-file, "
        "or set token_file in ~/.canvas.api.conf."
    )


def resolve_credentials(args, ap):
    """Resolve base_url and token from CLI args + profile config.

    Reads ~/.canvas.api.conf, fills in base_url and token from profile
    when not provided on the command line.  Calls ap.error() if base_url
    cannot be resolved.

    Returns (base_url, token).
    """
    profile = load_profile()
    if not args.base_url:
        args.base_url = profile.get("base_url")
    if not args.base_url:
        ap.error("--base-url is required (or set base_url in "
                 "~/.canvas.api.conf)")
    base_url = args.base_url.rstrip("/")
    token = read_token(args.token, args.token_file, profile)
    return base_url, token
